---
title: "Common regulator analysis"
output: html_notebook
date: "2024-12-10"
---
```{r setup}
library(tidyverse)
library(ggVennDiagram)
library(parallel)
source("local_settings.R")

# Set number of cores for parallelization
n_cores <- 8 
```

# Tal1, Gata2 and Gata3 (GABA and CO)

## GABA

```{r Fetching regulators for each selector TF in GABA}
Tal1_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Tal1", "GA1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=mean(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=min(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Gata2_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Gata2", "GA1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=mean(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=min(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Gata3_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Gata3", "GA1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=mean(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=min(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Combined.reg.tb <- rbind(Tal1_RE,Gata2_RE,Gata3_RE) %>% group_by(TF_gene_name) %>% summarize(linkpeaks_avg_pvalue=max(linkpeaks_avg_pvalue,na.rm=T))
```

```{r Finding common regulators for GABA selector TFs}
common_regulators.GABA <- tibble(
  TF_gene_name = intersect(intersect(Tal1_RE$TF_gene_name, Gata2_RE$TF_gene_name), Gata3_RE$TF_gene_name),
  present_in = "all")

common_regulators.GABA <- common_regulators.GABA %>%
  add_row(TF_gene_name = setdiff(intersect(Tal1_RE$TF_gene_name, Gata2_RE$TF_gene_name), Gata3_RE$TF_gene_name),
          present_in = "only Tal1 & Gata2") %>%
  add_row(TF_gene_name = setdiff(intersect(Tal1_RE$TF_gene_name, Gata3_RE$TF_gene_name), Gata2_RE$TF_gene_name),
          present_in = "only Tal1 & Gata3") %>%
  add_row(TF_gene_name = setdiff(intersect(Gata2_RE$TF_gene_name, Gata3_RE$TF_gene_name), Tal1_RE$TF_gene_name),
          present_in = "only Gata2 & Gata3") %>%
  add_row(TF_gene_name = setdiff(setdiff(Tal1_RE$TF_gene_name, Gata2_RE$TF_gene_name), Gata3_RE$TF_gene_name),
          present_in = "only Tal1") %>%
  add_row(TF_gene_name = setdiff(setdiff(Gata2_RE$TF_gene_name, Gata3_RE$TF_gene_name), Tal1_RE$TF_gene_name),
          present_in = "only Gata2") %>%
  add_row(TF_gene_name = setdiff(setdiff(Gata3_RE$TF_gene_name, Gata2_RE$TF_gene_name), Tal1_RE$TF_gene_name),
          present_in = "only Gata3")

common_regulators.GABA <- left_join(common_regulators.GABA,Combined.reg.tb)

write.csv(common_regulators.GABA, file = "../analysis/common_regulators.GABA.csv", row.names = FALSE, quote = FALSE)
```

```{r Venn diagram GABA}
common_regulator_list <- list(Tal1_RE$TF_gene_name, Gata2_RE$TF_gene_name, Gata3_RE$TF_gene_name)
common_regulator_venn <- ggVennDiagram(common_regulator_list, label_alpha = 0, category.names = c("Tal1", "Gata2", "Gata3")) +
  ggplot2::scale_fill_gradient(low = "white", high = "blue") + ggtitle("GABA") +
  scale_x_continuous(expand = expansion(mult = .3))
print(common_regulator_venn)
```

## CO

```{r Fetching regulators for each selector TF in CO}
Tal1_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Tal1", "CO1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=mean(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=min(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Gata2_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Gata2", "CO1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=mean(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=min(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Gata3_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Gata3", "CO1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=mean(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=min(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Combined.reg.tb <- rbind(Tal1_RE,Gata2_RE,Gata3_RE) %>% group_by(TF_gene_name) %>% summarize(linkpeaks_avg_pvalue=max(linkpeaks_avg_pvalue,na.rm=T))
```

```{r Finding common regulators for CO selector TFs}
common_regulators.CO <- tibble(
  TF_gene_name = intersect(intersect(Tal1_RE$TF_gene_name, Gata2_RE$TF_gene_name), Gata3_RE$TF_gene_name),
  present_in = "all")

common_regulators.CO <- common_regulators.CO %>%
  add_row(TF_gene_name = setdiff(intersect(Tal1_RE$TF_gene_name, Gata2_RE$TF_gene_name), Gata3_RE$TF_gene_name),
          present_in = "only Tal1 & Gata2") %>%
  add_row(TF_gene_name = setdiff(intersect(Tal1_RE$TF_gene_name, Gata3_RE$TF_gene_name), Gata2_RE$TF_gene_name),
          present_in = "only Tal1 & Gata3") %>%
  add_row(TF_gene_name = setdiff(intersect(Gata2_RE$TF_gene_name, Gata3_RE$TF_gene_name), Tal1_RE$TF_gene_name),
          present_in = "only Gata2 & Gata3") %>%
  add_row(TF_gene_name = setdiff(setdiff(Tal1_RE$TF_gene_name, Gata2_RE$TF_gene_name), Gata3_RE$TF_gene_name),
          present_in = "only Tal1") %>%
  add_row(TF_gene_name = setdiff(setdiff(Gata2_RE$TF_gene_name, Gata3_RE$TF_gene_name), Tal1_RE$TF_gene_name),
          present_in = "only Gata2") %>%
  add_row(TF_gene_name = setdiff(setdiff(Gata3_RE$TF_gene_name, Gata2_RE$TF_gene_name), Tal1_RE$TF_gene_name),
          present_in = "only Gata3")

common_regulators.CO <- left_join(common_regulators.CO,Combined.reg.tb)

write.csv(common_regulators.CO, file = "../analysis/common_regulators.CO.csv", row.names = FALSE, quote = FALSE)
```

```{r Venn diagram CO}
common_regulator_list <- list(Tal1_RE$TF_gene_name, Gata2_RE$TF_gene_name, Gata3_RE$TF_gene_name)
common_regulator_venn <- ggVennDiagram(common_regulator_list, label_alpha = 0, category.names = c("Tal1", "Gata2", "Gata3")) +
  ggplot2::scale_fill_gradient(low = "white", high = "blue") + ggtitle("CO") +
  scale_x_continuous(expand = expansion(mult = .3))
print(common_regulator_venn)
```

## Statistical testing

```{r}
# Example data (replace with your actual data):
A <- Tal1_RE$TF_gene_name
B <- Gata2_RE$TF_gene_name
C <- Gata3_RE$TF_gene_name

Universe <- fetch_all_regulators(db_path=paste(db.path,dbname.rV2,sep=""),zscore_threshold = 2, pvalue_threshold = 0.05)

# Observed intersection size
obs_intersect <- length(intersect(intersect(A, B), C))

# Number of permutations
N <- 1000000

# Define a single iteration function
random_intersect_fun <- function(i) {
  A_r <- sample(Universe, length(A))
  B_r <- sample(Universe, length(B))
  C_r <- sample(Universe, length(C))
  length(intersect(intersect(A_r, B_r), C_r))
}

# Run permutations in parallel
set.seed(2024) 
random_intersects <- mclapply(1:N, random_intersect_fun, mc.cores = n_cores)
random_intersects <- unlist(random_intersects)

# Compute empirical p-value
p_value <- mean(random_intersects >= obs_intersect)

# If p_value is 0 due to no permutations meeting or exceeding obs_intersect,
# print an upper bound for the p-value
if (p_value == 0) {
  cat("Observed intersection:", obs_intersect, "\n")
  cat("Empirical p-value: <", 1/(N + 1), "\n")
} else {
  cat("Observed intersection:", obs_intersect, "\n")
  cat("Empirical p-value:", p_value, "\n")
}
```

# Vsx1 and Vsx2 (GL and CO)

## GL

```{r Fetching regulators for each selector TF in GL}
Vsx1_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Vsx1", "GL1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=min(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=mean(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Vsx2_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Vsx2", "GL1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=min(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=mean(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Combined.reg.tb <- rbind(Vsx1_RE,Vsx2_RE) %>% group_by(TF_gene_name) %>% summarize(linkpeaks_avg_pvalue=max(linkpeaks_avg_pvalue,na.rm=T))
```

```{r Finding common regulators for GL selector TFs}
common_regulators.GL <- tibble(
TF_gene_name = intersect(Vsx1_RE$TF_gene_name, Vsx2_RE$TF_gene_name),
regulator = "all")

common_regulators.GL <- common_regulators.GL %>%
  add_row(TF_gene_name = setdiff(Vsx1_RE$TF_gene_name, Vsx2_RE$TF_gene_name),
          regulator = "only Vsx1") %>%
  add_row(TF_gene_name = setdiff(Vsx2_RE$TF_gene_name, Vsx1_RE$TF_gene_name),
          regulator = "only Vsx2")

common_regulators.GL <- left_join(common_regulators.GL,Combined.reg.tb)

write.csv(common_regulators.GL, file = "../analysis/common_regulators.GL.csv",row.names = FALSE, quote = FALSE)
```

```{r Venn diagram GL}
common_regulator_list <- list(Vsx1_RE$TF_gene_name, Vsx2_RE$TF_gene_name)
common_regulator_venn <- ggVennDiagram(common_regulator_list, label_alpha = 0, category.names = c("Vsx1", "Vsx2")) +
  ggplot2::scale_fill_gradient(low = "white", high = "blue") + ggtitle("GL") +
  scale_x_continuous(expand = expansion(mult = .3))
print(common_regulator_venn)
```

## CO

```{r Fetching regulators for each selector TF in CO #2}
Vsx1_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Vsx1", "CO1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=min(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=mean(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Vsx2_RE <-fetch.regulators_v2(db.name=paste(db.path,dbname.rV2,sep=""), "Vsx2", "CO1_2",pvalue.thr=0.05) %>% group_by(TF_gene_name, direction) %>% summarize(linkpeaks_avg_zscore=min(linkpeaks_zscore,na.rm=T), linkpeaks_avg_pvalue=mean(linkpeaks_pvalue, na.rm=T), direction=mean(direction))

Combined.reg.tb <- rbind(Vsx1_RE,Vsx2_RE) %>% group_by(TF_gene_name) %>% summarize(linkpeaks_avg_pvalue=max(linkpeaks_avg_pvalue,na.rm=T))
```

```{r Finding common regulators for CO selector TFs #2}
common_regulators.CO_2 <- tibble(
TF_gene_name = intersect(Vsx1_RE$TF_gene_name, Vsx2_RE$TF_gene_name),
regulator = "all")

common_regulators.CO_2 <- common_regulators.CO_2 %>%
  add_row(TF_gene_name = setdiff(Vsx1_RE$TF_gene_name, Vsx2_RE$TF_gene_name),
          regulator = "only Vsx1") %>%
  add_row(TF_gene_name = setdiff(Vsx2_RE$TF_gene_name, Vsx1_RE$TF_gene_name),
          regulator = "only Vsx2")

common_regulators.CO_2 <- left_join(common_regulators.CO_2,Combined.reg.tb)

write.csv(common_regulators.CO_2, file = "../analysis/common_regulators.CO_GL.csv", row.names = FALSE, quote = FALSE)
```

```{r Venn diagram CO #2}
common_regulator_list <- list(Vsx1_RE$TF_gene_name, Vsx2_RE$TF_gene_name)
common_regulator_venn <- ggVennDiagram(common_regulator_list, label_alpha = 0, category.names = c("Vsx1", "Vsx2")) +
  ggplot2::scale_fill_gradient(low = "white", high = "blue") + ggtitle("GL") +
  scale_x_continuous(expand = expansion(mult = .3))
print(common_regulator_venn)
```


```{r}
sessionInfo()
```

