---
title: "Conservation summary"
output: html_document
date: '2023-11-13'
---

```{r}
library(tidyverse)
```

```{r Load data}
feat <- readRDS("/Users/kilpinen/OneDrive - University of Helsinki/E12R1 project/Heidi/Data/IGV/conservation_data/fishers_exact_test_results_ATAC_features.rds")
exons <- readRDS("/Users/kilpinen/OneDrive - University of Helsinki/E12R1 project/Heidi/Data/IGV/conservation_data/fishers_exact_test_results_exons_per_chromosome.rds")
introns <- readRDS("/Users/kilpinen/OneDrive - University of Helsinki/E12R1 project/Heidi/Data/IGV/conservation_data/fishers_exact_test_results_introns_per_chromosome.rds")
```


```{r Gather cons stats into long tibble}
exons.ORs <- sapply(exons[which(grepl(x=names(exons), pattern = ".*results"))],function(e){e$estimate})
introns.ORs <- sapply(introns[which(grepl(x=names(introns), pattern = ".*results"))],function(e){e$estimate})
feat.ORs <- sapply(feat[which(grepl(x=names(feat), pattern = ".*results"))],function(e){e$estimate})

exons.p <- sapply(exons[which(grepl(x=names(exons), pattern = ".*results"))],function(e){e$p.value})
introns.p <- sapply(introns[which(grepl(x=names(introns), pattern = ".*results"))],function(e){e$p.value})
feat.p <- sapply(feat[which(grepl(x=names(feat), pattern = ".*results"))],function(e){e$p.value})

cons.data.res.tb <- tibble(chr=rep(paste("chr",seq(1,19,by=1),sep=""),3),ORs=c(exons.ORs,introns.ORs,feat.ORs), region.type=c(rep("exon",19),rep("intron",19),rep("feature",19)), p.vals=c(exons.p,introns.p,feat.p))
```

```{r Creatre grouped barplot of ORs}
ORs.plot <- ggplot(cons.data.res.tb, aes(y=ORs, fill=region.type, x=chr)) + geom_bar(position="dodge", stat="identity") + ylab("Odds ratio") + theme_minimal(axis.text.x = element_text(size=14, angle=45))

plot_loc <- "~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/FigS4/"
plot_name <- paste("Conservation_ORs.pdf",sep="")

ggsave(filename = plot_name,
         plot = ORs.plot,
         path = plot_loc,
         device = "pdf",
         width = 15,
         height = 15,
         units = "in")
```


