---
title: "R Notebook"
output: html_notebook
---

```{r}
library(netZooR)
library(qs)
library(Seurat)
library(Signac)
library(GenomicRanges)
library(tidyverse)
library(hash)
library(DBI)
cores<-8
```

```{r}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "~/Workspace/TOBIAS.dr.h12_230424.sqlite")
options(timeout = 30000)
```


```{r Reading Seurat dataobject}
dataset <- qread("../scATAC_data/nmm_rV2_subset_relabeled_031023_links.qs", nthreads = cores)
DefaultAssay(dataset) <- "RNA"

dataset$rv2.lineage_re <- case_when(
  dataset$rv2.lineage %in% "PRO1" ~ "PRO1_2",
  dataset$rv2.lineage %in% "PRO2" ~ "PRO1_2",
  dataset$rv2.lineage %in% "GA1" ~ "GA1_2",
  dataset$rv2.lineage %in% "GA2" ~ "GA1_2",
  dataset$rv2.lineage %in% "GA3" ~ "GA3_4",
  dataset$rv2.lineage %in% "GA4" ~ "GA3_4",
  dataset$rv2.lineage %in% "GA5" ~ "GA5_6",
  dataset$rv2.lineage %in% "GA6" ~ "GA5_6",
  dataset$rv2.lineage %in% "CO1" ~ "CO1_2",
  dataset$rv2.lineage %in% "CO2" ~ "CO1_2",
  dataset$rv2.lineage %in% "GL1" ~ "GL1_2",
  dataset$rv2.lineage %in% "GL2" ~ "GL1_2",
  dataset$rv2.lineage %in% "GL3" ~ "GL3_4",
  dataset$rv2.lineage %in% "GL4" ~ "GL3_4",
  dataset$rv2.lineage %in% "GL5" ~ "GL5",
)

DefaultAssay(dataset) <- "peaks"
all.features <- StringToGRanges(rownames(dataset))

gene_id2name <- hash(rownames(dataset[['RNA']][[]]),dataset[['RNA']][[]][,1])
gene_name2id <- hash(dataset[['RNA']][[]][,1],rownames(dataset[['RNA']][[]]))
```

```{r Fetch data layers for graph building}
DefaultAssay(dataset) <- "RNA"
exp.data <- FetchData(object = dataset, vars = rownames(dataset))

DefaultAssay(dataset) <- "peaks"
acc.data <- FetchData(object = dataset, vars = rownames(dataset))
```

```{r Define cell groups and linked features}
CO1_2.li <- dataset$rv2.lineage_re=="CO1_2"

linked.features <- as_tibble(dbGetQuery(con, 'SELECT feature FROM links as li WHERE ABS(li.zscore)>2 AND li.pvalue<0.001;')) %>% pull(feature)
linked.genes <- unique(as_tibble(dbGetQuery(con, 'SELECT ensg_id FROM links as li WHERE ABS(li.zscore)>2 AND li.pvalue<0.001;')) %>% pull(ensg_id))

DefaultAssay(dataset) <- "RNA"
all.genes <- rownames(dataset)
genes.li <- all.genes %in% linked.genes

DefaultAssay(dataset) <- "peaks"
all.features <- rownames(dataset)
features.li <- all.features %in% linked.features
```

```{r Subset datamatrices}
exp.CO1_2 <- exp.data[CO1_2.li,genes.li][,sample(1:ncol(exp.data[,genes.li]),150, replace = FALSE)]
acc.CO1_2 <- acc.data[CO1_2.li,features.li][,sample(1:ncol(acc.data[,features.li]),150, replace = FALSE)]

exp.CO1_2 <- exp.CO1_2[,which(!colSums(exp.CO1_2)==0)]
acc.CO1_2 <- acc.CO1_2[,which(!colSums(acc.CO1_2)==0)]
```

```{r Run Dragon}
CO1_2.dragon <- dragon(layer1=exp.CO1_2, layer2 = acc.CO1_2, verbose=TRUE)
```

```{r}
sessionInfo()
```

