---
title: "recreate_seurat_data"
output: html_document
---

Rerun Seurat workflow for all scRNA data sets. Main difference in parameter tuning and scaling: more unified QC parameters, using 3000 most variable features and regressing out nuisance parameters.


```{r}
.libPaths(c("/projappl/project_2001539/project_rpackages_r404", .libPaths()))
libpath <- .libPaths()[1]

library(Seurat, lib.loc = libpath)
library(tidyverse, lib.loc = libpath)
source("/scratch/project_2001539/lassi/src/Aux/convert_feature_id.R")

set.seed(42)
```

```{r}
# Run prior Seurat 4.0.5, otherwise skipped (for reproducibility) 
options(parallelly.makeNodePSOCK.setup_strategy = "sequential", future.globals.maxSize = 12 * 1024 ^ 3, future.seed = T)
future::plan("multisession", workers = 6)
```

```{r}
e12.locs <- c("../scRNA_data/153-1-F/outs/filtered_feature_bc_matrix/",
              "../scRNA_data/153-7-F/outs/filtered_feature_bc_matrix/",
              "../scRNA_data/153-4-M/outs/filtered_feature_bc_matrix/",
              "../scRNA_data/153-5-M/outs/filtered_feature_bc_matrix/")

e13.locs <- c("../scRNA_data/E13_vR1/outs_r1-6/filtered_feature_bc_matrix",
              "../scRNA_data/E13_vR1/outs_r1-7/filtered_feature_bc_matrix",
              "../scRNA_data/E13_vR1/outs_r1-12/filtered_feature_bc_matrix")

e14.locs <- c("../scRNA_data/E14_vR1_1_RNA/outs/filtered_feature_bc_matrix",
              "../scRNA_data/E14_vR1_2_RNA/outs/filtered_feature_bc_matrix")

e15.locs <- c("../scRNA_data/E15_vR1_1_tdT/outs/filtered_feature_bc_matrix",
              "../scRNA_data/E15_vR1_2_tdT/outs/filtered_feature_bc_matrix",
              "../scRNA_data/E15_vR1_7_tdT/outs/filtered_feature_bc_matrix")

e12.feat.loc <- "../scRNA_data/153-1-F/outs/filtered_feature_bc_matrix/features.tsv.gz"
e13.feat.loc <- "../scRNA_data/E13_vR1/outs_r1-6/filtered_feature_bc_matrix/genes.tsv"
e14.feat.loc <- "../scRNA_data/E14_vR1_1_RNA/outs/filtered_feature_bc_matrix/features.tsv.gz"
e15.feat.loc <- "../scRNA_data/E15_vR1_1_tdT/outs/filtered_feature_bc_matrix/features.tsv.gz"
```


```{r import raw data files}
# Import E1x.5 raw data files with gene.column = 1 = ENSEMBL ID names instead of gene symbols

e12.1f <- Read10X(e12.locs[1], gene.column = 1, strip.suffix = T)
e12.7f <- Read10X(e12.locs[2], gene.column = 1, strip.suffix = T)
e12.4m <- Read10X(e12.locs[3], gene.column = 1, strip.suffix = T)
e12.5m <- Read10X(e12.locs[4], gene.column = 1, strip.suffix = T)

e13.6 <- Read10X(e13.locs[1], gene.column = 1, strip.suffix = T)
e13.7 <- Read10X(e13.locs[2], gene.column = 1, strip.suffix = T)
e13.12 <- Read10X(e13.locs[3], gene.column = 1, strip.suffix = T)

e14.1 <- Read10X(e14.locs[1], gene.column = 1)
e14.2 <- Read10X(e14.locs[2], gene.column = 1)

e15.1 <- Read10X(e15.locs[1], gene.column = 1, strip.suffix = T)
e15.2 <- Read10X(e15.locs[2], gene.column = 1, strip.suffix = T)
e15.7 <- Read10X(e15.locs[3], gene.column = 1, strip.suffix = T)
```

```{r import tsvs of features with ensembl-symbol mapping}
e12.features <- read.csv(e12.feat.loc, sep = "\t", header = F) %>% tibble %>% rename("ENSEMBL_ID" = "V1", "gene_symbol" = "V2", "gene_expression" = "V3")

e13.features <- read.csv(e13.feat.loc, sep = "\t", header = F) %>% tibble %>% rename("ENSEMBL_ID" = "V1", "gene_symbol" = "V2", "gene_expression" = "V3")

e14.features <- read.csv(e14.feat.loc, sep = "\t", header = F) %>% tibble %>% rename("ENSEMBL_ID" = "V1", "gene_symbol" = "V2", "gene_expression" = "V3")

e15.features <- read.csv(e15.feat.loc, sep = "\t", header = F) %>% tibble %>% rename("ENSEMBL_ID" = "V1", "gene_symbol" = "V2", "gene_expression" = "V3")

features.for.metadata <- list(e12.features, e13.features, e14.features, e15.features)
```

```{r create seurat objectes and combine to large list}
e12.list <- lapply(list(e12.1f, e12.7f, e12.4m, e12.5m), CreateSeuratObject)
e13.list <- lapply(list(e13.6, e13.7, e13.12), CreateSeuratObject)
e14.list <- lapply(list(e14.1, e14.2), CreateSeuratObject)
e15.list <- lapply(list(e15.1, e15.2, e15.7), CreateSeuratObject)

e12.list <- merge(e12.list[[1]], c(e12.list[[2]], e12.list[[3]], e12.list[[4]]), 
                  add.cell.ids = c("1F", "7F", "4M", "5M"))
e13.list <- merge(e13.list[[1]], c(e13.list[[2]], e13.list[[3]]),
                  add.cell.ids = c("R1.6", "R1.7", "R1.12"))
e14.list <- merge(e14.list[[1]], e14.list[[2]],
                  add.cell.ids = c("repl1", "repl2"))
e15.list <- merge(e15.list[[1]], c(e15.list[[2]], e15.list[[3]]),
                  add.cell.ids = c("E15.R1.1", "E15.R1.2", "E15.R1.7"))

e.all.combined <- list(e12.list, e13.list, e14.list, e15.list)
names(e.all.combined) <- c("e12", "e13", "e14", "e15")
```

```{r add feature metadata containing features from previous block}
for (idx in 1:length(e.all.combined)) {

   e.all.combined[[idx]][["RNA"]] <- AddMetaData(
     object = e.all.combined[[idx]][["RNA"]],
     metadata = features.for.metadata[[idx]]$gene_symbol,
     col.name = "feature_symbol")

}
```

```{r mitcochondrial features}
for (idx in 1:length(e.all.combined)) {

  # Get mt gene symbols
  feature.map <- e.all.combined[[idx]]@assays[["RNA"]]@meta.features[["feature_symbol"]]
  # Get corresponding ensembl ids
  mt.features <- rownames(e.all.combined[[idx]])[grep("^MT-",
                                                      feature.map,
                                                      ignore.case = T)]
  # Add mt percentages to metadata
  e.all.combined[[idx]][["percent.mt"]] <- PercentageFeatureSet(e.all.combined[[idx]],
                                                                features = mt.features)

}
```

```{r generate plot QC}
nfeature.plot.list <- lapply(1:length(e.all.combined), function(idx) {
  t.p <- names(e.all.combined)[idx]
  plt <- VlnPlot(e.all.combined[[idx]], features = "nFeature_RNA") + 
    ggtitle(t.p) +
    NoLegend()
})

ncount.plot.list <- lapply(1:length(e.all.combined), function(idx) {
  t.p <- names(e.all.combined)[idx]
  plt <- VlnPlot(e.all.combined[[idx]], features = "nCount_RNA") + 
    ggtitle(t.p) +
    NoLegend()
})

pctmt.plot.list <- lapply(1:length(e.all.combined), function(idx) {
  t.p <- names(e.all.combined)[idx]
  plt <- VlnPlot(e.all.combined[[idx]], features = "percent.mt") + 
    ggtitle(t.p) +
    NoLegend()
})

```

```{r}
patchwork::wrap_plots(
  nfeature.plot.list[[1]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(nfeature.plot.list[[1]]$data$nFeature_RNA),
                                               by = 500))),
  nfeature.plot.list[[2]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(nfeature.plot.list[[2]]$data$nFeature_RNA),
                                               by = 500))),
  nfeature.plot.list[[3]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(nfeature.plot.list[[3]]$data$nFeature_RNA),
                                               by = 500))),
  nfeature.plot.list[[4]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(nfeature.plot.list[[4]]$data$nFeature_RNA),
                                               by = 500))),
  ncol = 4
)
```

```{r}
patchwork::wrap_plots(
  ncount.plot.list[[1]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(ncount.plot.list[[1]]$data$nCount_RNA),
                                               by = 10000))),
  ncount.plot.list[[2]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(ncount.plot.list[[2]]$data$nCount_RNA),
                                               by = 10000))),
  ncount.plot.list[[3]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(ncount.plot.list[[3]]$data$nCount_RNA),
                                               by = 10000))),
  ncount.plot.list[[4]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(ncount.plot.list[[4]]$data$nCount_RNA),
                                               by = 10000))),
  ncol = 4
)
```

```{r}
patchwork::wrap_plots(
  pctmt.plot.list[[1]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(pctmt.plot.list[[1]]$data$percent.mt),
                                               by = 5))),
  pctmt.plot.list[[2]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(pctmt.plot.list[[2]]$data$percent.mt),
                                               by = 5))),
  pctmt.plot.list[[3]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(pctmt.plot.list[[3]]$data$percent.mt),
                                               by = 5))),
  pctmt.plot.list[[4]] + scale_y_continuous(breaks = round(x = seq(0,
                                               max(pctmt.plot.list[[4]]$data$percent.mt),
                                               by = 5))),
  ncol = 4
)
```

```{r QC}
# nFeature_RNA lower bounds for QC filtering
nf.lb <- c(3000, 3000, 3000, 2500)
# nFeature_RNA upper bounds for QC filtering
nf.ub <- c(5500, 5000, 5000, 5000)
# Mt pct upper bounds for QC filtering
pctmt.ub <- rep(10, 4)

e.all.combined <- lapply(1:length(e.all.combined), function (idx) {
  subset(e.all.combined[[idx]],
         subset = nFeature_RNA > nf.lb[idx] & nFeature_RNA < nf.ub[idx] & percent.mt < pctmt.ub[idx])
})
```

Summarizing

```{r}
VlnPlot(e.all.combined[[1]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
VlnPlot(e.all.combined[[2]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
VlnPlot(e.all.combined[[3]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
VlnPlot(e.all.combined[[4]], features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

#### Normalization

```{r normalization}
for (idx in 1:length(e.all.combined)) {
  e.all.combined[[idx]] <-
    NormalizeData(e.all.combined[[idx]],
                  normalization.method = "LogNormalize",
                  scale.factor = 10000,
                  verbose = F) %>% 
    FindVariableFeatures(selection.method = "vst",
                         nfeatures = 3000,
                         verbose = F)
    
}
```

### Scaling

```{r scaling}
for (idx in 1:length(e.all.combined)) {
  # Keep track which one is being processed
  print(idx)
  # preferably NOT RUN, runs for > 10 hours
  e.all.combined[[idx]] <- ScaleData(e.all.combined[[idx]],
                                     features = rownames(e.all.combined[[idx]]),
                                     vars.to.regress = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                                     verbose = F)
}
```

```{r save intermediate result}
run.this <- F

if (run.this) {
  # Data object saved to avoid running heavy computation repetitively
  saveRDS(e.all.combined, "../scRNA_data/e_all_rescaled_regress_nuisance.Rds")  
}
```

```{r}
sessionInfo()
```