---
title: "R Notebook"
output: html_document
---

```{r, message=FALSE}
library(tidyverse)
library(DBI)
library(readxl)
library(writexl)
library(GenomicRanges)
library(qs)
source("local_settings.R")
```

```{r DB conection and loading objects, message=FALSE}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname = paste(db.path,dbname.rV2,sep=""))
gene_name2id <- qread("gene_name2id.qs", nthreads = cores)
```

## Gata2

```{r Old archived table}
Gata2.features <- readxl::read_xlsx(paste(archived.table.loc,"Gata2 feature summary_new.xlsx",sep=""), sheet = "Sheet1")
```

```{r Regenerate from db}
gene_name <- "Gata2"
distance.limit <- 0
# Construct the SQL query using paste0()
query <- paste0("
WITH gene_tads AS (
  SELECT DISTINCT t.seqnames, t.start, t.end, g.TSS_start, g.gene_end, g.strand
  FROM TAD t
  JOIN gene_metadata g ON t.seqnames = g.seqnames
  WHERE g.gene_name = '", gene_name, "'
    AND g.gene_end >= t.start
    AND g.TSS_start <= t.end
)
SELECT DISTINCT f.*, 
       GROUP_CONCAT(DISTINCT gm.gene_name) AS gene_identity,
       CASE 
         WHEN gt.strand = '+' THEN 
           (f.start + (f.end - f.start) / 2) - gt.TSS_start
         WHEN gt.strand = '-' THEN 
           gt.TSS_start - (f.start + (f.end - f.start) / 2)
         ELSE NULL
       END AS Gene_TSS_distance,
       CASE 
         WHEN (CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) >= 0 THEN '+' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
         ELSE '-' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
       END AS gene_feature_name,
       l.zscore, l.pvalue
FROM feature f
JOIN (
  SELECT DISTINCT seqnames, start, end, TSS_start, strand 
  FROM gene_tads
) gt ON f.seqnames = gt.seqnames
LEFT JOIN gene_metadata gm ON f.seqnames = gm.seqnames
  AND ((gm.strand = '+' AND f.end > gm.TSS_start AND f.start < gm.gene_end)
       OR (gm.strand = '-' AND f.start < gm.TSS_start AND f.end > gm.gene_end))
LEFT JOIN links_s l ON f.feature = l.feature AND l.ensg_id = '", gene_name2id[[gene_name]], "'
WHERE f.end > gt.start
  AND f.start < gt.end
GROUP BY f.seqnames, f.start, f.end, gt.TSS_start, gt.strand, l.zscore, l.pvalue;
")
# Execute the query and fetch results
result.Gata2 <- as_tibble(dbGetQuery(con, query)) %>% mutate(gene_feature_name=as.character(gene_feature_name))
```

```{r Write to Excel, eval=FALSE}
writexl::write_xlsx(result.Gata2, path=paste(table.loc,"Gata2_features.xlsx",sep=""))
```

## Gata3

```{r Old archived table}
Gata3.features <- readxl::read_xlsx(paste(archived.table.loc,"Gata3 feature summary_new.xlsx",sep=""), sheet = "Sheet1")
```

```{r Regenerate from db}
gene_name <- "Gata3"

# Construct the SQL query using paste0()
query <- paste0("
WITH gene_tads AS (
  SELECT DISTINCT t.seqnames, t.start, t.end, g.TSS_start, g.gene_end, g.strand
  FROM TAD t
  JOIN gene_metadata g ON t.seqnames = g.seqnames
  WHERE g.gene_name = '", gene_name, "'
    AND g.gene_end >= t.start
    AND g.TSS_start <= t.end
)
SELECT DISTINCT f.*, 
       GROUP_CONCAT(DISTINCT gm.gene_name) AS gene_identity,
       CASE 
         WHEN gt.strand = '+' THEN 
           (f.start + (f.end - f.start) / 2) - gt.TSS_start
         WHEN gt.strand = '-' THEN 
           gt.TSS_start - (f.start + (f.end - f.start) / 2)
         ELSE NULL
       END AS Gene_TSS_distance,
       CASE 
         WHEN (CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) >= 0 THEN '+' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
         ELSE '-' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
       END AS gene_feature_name,
       l.zscore, l.pvalue
FROM feature f
JOIN (
  SELECT DISTINCT seqnames, start, end, TSS_start, strand 
  FROM gene_tads
) gt ON f.seqnames = gt.seqnames
LEFT JOIN gene_metadata gm ON f.seqnames = gm.seqnames
  AND ((gm.strand = '+' AND f.end > gm.TSS_start AND f.start < gm.gene_end)
       OR (gm.strand = '-' AND f.start < gm.TSS_start AND f.end > gm.gene_end))
LEFT JOIN links_s l ON f.feature = l.feature AND l.ensg_id = '", gene_name2id[[gene_name]], "'
WHERE f.end > gt.start
  AND f.start < gt.end
GROUP BY f.seqnames, f.start, f.end, gt.TSS_start, gt.strand, l.zscore, l.pvalue;
")

# Execute the query and fetch results
result.Gata3 <- as_tibble(dbGetQuery(con, query)) %>% mutate(gene_feature_name=as.character(gene_feature_name))
```

```{r Write to Excel, eval=FALSE}
writexl::write_xlsx(result.Gata3, path=paste(table.loc,gene_name,"_features.xlsx",sep=""))
```

## Tal1

```{r Old archived table}
Tal1.features <- readxl::read_xlsx(paste(archived.table.loc,"Tal1 feature summary_new_2.xlsx",sep=""), sheet = "Sheet1")
```

```{r Regenerate from db}
gene_name <- "Tal1"

# Construct the SQL query using paste0()
query <- paste0("
WITH gene_tads AS (
  SELECT DISTINCT t.seqnames, t.start, t.end, g.TSS_start, g.gene_end, g.strand
  FROM TAD t
  JOIN gene_metadata g ON t.seqnames = g.seqnames
  WHERE g.gene_name = '", gene_name, "'
    AND g.gene_end >= t.start
    AND g.TSS_start <= t.end
)
SELECT DISTINCT f.*, 
       GROUP_CONCAT(DISTINCT gm.gene_name) AS gene_identity,
       CASE 
         WHEN gt.strand = '+' THEN 
           (f.start + (f.end - f.start) / 2) - gt.TSS_start
         WHEN gt.strand = '-' THEN 
           gt.TSS_start - (f.start + (f.end - f.start) / 2)
         ELSE NULL
       END AS Gene_TSS_distance,
       CASE 
         WHEN (CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) >= 0 THEN '+' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
         ELSE '-' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
       END AS gene_feature_name,
       l.zscore, l.pvalue
FROM feature f
JOIN (
  SELECT DISTINCT seqnames, start, end, TSS_start, strand 
  FROM gene_tads
) gt ON f.seqnames = gt.seqnames
LEFT JOIN gene_metadata gm ON f.seqnames = gm.seqnames
  AND ((gm.strand = '+' AND f.end > gm.TSS_start AND f.start < gm.gene_end)
       OR (gm.strand = '-' AND f.start < gm.TSS_start AND f.end > gm.gene_end))
LEFT JOIN links_s l ON f.feature = l.feature AND l.ensg_id = '", gene_name2id[[gene_name]], "'
WHERE f.end > gt.start
  AND f.start < gt.end
GROUP BY f.seqnames, f.start, f.end, gt.TSS_start, gt.strand, l.zscore, l.pvalue;
")

# Execute the query and fetch results
result.Tal1 <- as_tibble(dbGetQuery(con, query)) %>% mutate(gene_feature_name=as.character(gene_feature_name))
```

```{r Write to Excel, eval=FALSE}
writexl::write_xlsx(result.Tal1, path=paste(table.loc,gene_name,"_features.xlsx",sep=""))
```

## Vsx2

```{r Old archived table}
Vsx2.features <- readxl::read_xlsx(paste(archived.table.loc,"Vsx2 feature summary_new.xlsx",sep=""), sheet = "Sheet1")
```

```{r Regenerate from db Vsx2 links_s}
gene_name <- "Vsx2"

# Construct the SQL query using paste0()
query <- paste0("
WITH gene_tads AS (
  SELECT DISTINCT t.seqnames, t.start, t.end, g.TSS_start, g.gene_end, g.strand
  FROM TAD t
  JOIN gene_metadata g ON t.seqnames = g.seqnames
  WHERE g.gene_name = '", gene_name, "'
    AND g.gene_end >= t.start
    AND g.TSS_start <= t.end
)
SELECT DISTINCT f.*, 
       GROUP_CONCAT(DISTINCT gm.gene_name) AS gene_identity,
       CASE 
         WHEN gt.strand = '+' THEN 
           (f.start + (f.end - f.start) / 2) - gt.TSS_start
         WHEN gt.strand = '-' THEN 
           gt.TSS_start - (f.start + (f.end - f.start) / 2)
         ELSE NULL
       END AS Gene_TSS_distance,
       CASE 
         WHEN (CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) >= 0 THEN '+' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
         ELSE '-' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
       END AS gene_feature_name,
       l.zscore, l.pvalue
FROM feature f
JOIN (
  SELECT DISTINCT seqnames, start, end, TSS_start, strand 
  FROM gene_tads
) gt ON f.seqnames = gt.seqnames
LEFT JOIN gene_metadata gm ON f.seqnames = gm.seqnames
  AND ((gm.strand = '+' AND f.end > gm.TSS_start AND f.start < gm.gene_end)
       OR (gm.strand = '-' AND f.start < gm.TSS_start AND f.end > gm.gene_end))
LEFT JOIN links_s l ON f.feature = l.feature AND l.ensg_id = '", gene_name2id[[gene_name]], "'
WHERE f.end > gt.start
  AND f.start < gt.end
GROUP BY f.seqnames, f.start, f.end, gt.TSS_start, gt.strand, l.zscore, l.pvalue;
")

# Execute the query and fetch results
result.Vsx2 <- as_tibble(dbGetQuery(con, query)) %>% mutate(gene_feature_name=as.character(gene_feature_name))

#result.Vsx2 <- left_join(result, select(Vsx2.features, Feature, Gene_identity, Comment, Ref), by=c("feature"="Feature"))
writexl::write_xlsx(result.Vsx2, path=paste(table.loc,gene_name,"_features_s.xlsx",sep=""))
```

```{r Write to Excel, eval=FALSE}
writexl::write_xlsx(result.Vsx2, path=paste(table.loc,gene_name,"_features.xlsx",sep=""))
```

```{r Regenerate from db Vsx2 links PEARSON, eval=FALSE}
gene_name <- "Vsx2"

# Construct the SQL query using paste0()
query <- paste0("
WITH gene_tads AS (
  SELECT DISTINCT t.seqnames, t.start, t.end, g.TSS_start, g.gene_end, g.strand
  FROM TAD t
  JOIN gene_metadata g ON t.seqnames = g.seqnames
  WHERE g.gene_name = '", gene_name, "'
    AND g.gene_end >= t.start
    AND g.TSS_start <= t.end
)
SELECT DISTINCT f.*, 
       GROUP_CONCAT(DISTINCT gm.gene_name) AS gene_identity,
       CASE 
         WHEN gt.strand = '+' THEN 
           (f.start + (f.end - f.start) / 2) - gt.TSS_start
         WHEN gt.strand = '-' THEN 
           gt.TSS_start - (f.start + (f.end - f.start) / 2)
         ELSE NULL
       END AS Gene_TSS_distance,
       CASE 
         WHEN (CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) >= 0 THEN '+' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
         ELSE '-' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
       END AS gene_feature_name,
       l.zscore, l.pvalue
FROM feature f
JOIN (
  SELECT DISTINCT seqnames, start, end, TSS_start, strand 
  FROM gene_tads
) gt ON f.seqnames = gt.seqnames
LEFT JOIN gene_metadata gm ON f.seqnames = gm.seqnames
  AND ((gm.strand = '+' AND f.end > gm.TSS_start AND f.start < gm.gene_end)
       OR (gm.strand = '-' AND f.start < gm.TSS_start AND f.end > gm.gene_end))
LEFT JOIN links l ON CAST(f.feature AS TEXT) = CAST(l.feature AS TEXT) AND l.ensg_id = '", gene_name2id[[gene_name]], "'
WHERE f.end > gt.start
  AND f.start < gt.end
GROUP BY f.seqnames, f.start, f.end, gt.TSS_start, gt.strand, l.zscore, l.pvalue;
")

# Execute the query and fetch results
result.Vsx2 <- as_tibble(dbGetQuery(con, query)) %>% mutate(gene_feature_name=as.character(gene_feature_name))

#result.Vsx2 <- left_join(result, select(Vsx2.features, Feature, Gene_identity, Comment, Ref), by=c("feature"="Feature"))
writexl::write_xlsx(result.Vsx2, path=paste(table.loc,gene_name,"_features_p.xlsx",sep=""))
```

## Vsx1

```{r}
gene_name <- "Vsx1"

# Construct the SQL query using paste0()
query <- paste0("
WITH gene_tads AS (
  SELECT DISTINCT t.seqnames, t.start, t.end, g.TSS_start, g.gene_end, g.strand
  FROM TAD t
  JOIN gene_metadata g ON t.seqnames = g.seqnames
  WHERE g.gene_name = '", gene_name, "'
    AND g.gene_end >= t.start
    AND g.TSS_start <= t.end
)
SELECT DISTINCT f.*, 
       GROUP_CONCAT(DISTINCT gm.gene_name) AS gene_identity,
       CASE 
         WHEN gt.strand = '+' THEN 
           (f.start + (f.end - f.start) / 2) - gt.TSS_start
         WHEN gt.strand = '-' THEN 
           gt.TSS_start - (f.start + (f.end - f.start) / 2)
         ELSE NULL
       END AS Gene_TSS_distance,
       CASE 
         WHEN (CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) >= 0 THEN '+' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
         ELSE '-' || ROUND(ABS((CASE 
           WHEN gt.strand = '+' THEN 
             (f.start + (f.end - f.start) / 2) - gt.TSS_start
           WHEN gt.strand = '-' THEN 
             gt.TSS_start - (f.start + (f.end - f.start) / 2)
           ELSE NULL
         END) / 1000.0), 1)
       END AS gene_feature_name,
       l.zscore, l.pvalue
FROM feature f
JOIN (
  SELECT DISTINCT seqnames, start, end, TSS_start, strand 
  FROM gene_tads
) gt ON f.seqnames = gt.seqnames
LEFT JOIN gene_metadata gm ON f.seqnames = gm.seqnames
  AND ((gm.strand = '+' AND f.end > gm.TSS_start AND f.start < gm.gene_end)
       OR (gm.strand = '-' AND f.start < gm.TSS_start AND f.end > gm.gene_end))
LEFT JOIN links_s l ON f.feature = l.feature AND l.ensg_id = '", gene_name2id[[gene_name]], "'
WHERE f.end > gt.start
  AND f.start < gt.end
GROUP BY f.seqnames, f.start, f.end, gt.TSS_start, gt.strand, l.zscore, l.pvalue;
")
# Execute the query and fetch results
result.Vsx1 <- as_tibble(dbGetQuery(con, query)) %>% mutate(gene_feature_name=as.character(gene_feature_name))
```

```{r Write to Excel, eval=FALSE}
writexl::write_xlsx(result.Vsx1, path=paste(table.loc,gene_name,"_features.xlsx",sep=""))
```

```{r}
# Row-bind the tibbles with an additional column for gene names
combined_tibble <- bind_rows(list(result.Gata2, result.Gata3, result.Tal1, result.Vsx2,result.Vsx1), .id = "gene_name")
```

```{r}
dbDisconnect(con)
```

```{r, eval=FALSE}
saveRDS(combined_tibble,file="../analysis/Selector.features.Rds")
```

```{r}
sessionInfo()
```

