---
title: "R Notebook of rV2 manuscript figure 2A"
output: html_document
---

```{r Packages, echo=FALSE}
library(tidyverse)
library(Seurat)
library(Signac)
library(qs)
library(rtracklayer)
library(gUtils)
source("AuxFunctions.R")
```

```{r Set parameters}
cores <- 6
```

```{r Load qs object}
rV2.data <- qread("../scATAC_data/nmm_rV2_subset_relabeled_031023_links.qs", nthreads = cores)
DefaultAssay(rV2.data) <- "peaks"
rV2.data$rv2.lineage <- factor(rV2.data$rv2.lineage, levels=c("PRO1","PRO2","CO1", "CO2", "GA1", "GA2", "GA3", "GA4", "GA5", "GA6", "GL1", "GL2", "GL3", "GL4", "GL5"))
all.features.gr <- StringToGRanges(rownames(rV2.data))
```

```{r}
# Gene annotations from EnsDb 
annotations <- readRDS("../metadata/Ensembel_Mmusculus79_annotation.Rds")

# Change to UCSC style
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "mm10"

# Add the gene information to the object
Signac::Annotation(rV2.data) <- annotations
```

```{r Update fragment file locations, eval=FALSE}
frags <- Fragments(rV2.data)
Fragments(rV2.data)<-NULL

new.paths = list("/Volumes/MyBookDuo/Data/e12r1_data/scATAC/E12_R1_1/outs/fragments.filtered.tsv.gz","/Volumes/MyBookDuo/Data/e12r1_data/scATAC/E12_R1_2/outs/fragments.filtered.tsv.gz")

for (i in seq_along(frags)) {
  frags[[i]] <- UpdatePath(frags[[i]], new.path = new.paths[[i]]) # update path
}

Fragments(rV2.data)<-frags
```

```{r Read conservation data}
cons.gr <- qread("../metadata/cons.filt.gr.qs", nthreads = cores)
cons.gr.reduced <- GenomicRanges::reduce(cons.gr)
```

# Tal1 region plot

```{r Set gene regions}
gene.of.interest <- "Tal1"
f1.range <- range(Annotation(rV2.data)[Annotation(rV2.data)$gene_name %in% gene.of.interest], ignore.strand = TRUE)
f2.range <- f1.range+50000
```

```{r Read and subset conservation data, eval=FALSE}
cons.gr <- import.bw(con="../metadata/mm10.60way.phastCons.bw",as="GRanges")
cons.filt.gr <- cons.gr[(elementMetadata(cons.gr)[, "score"]>=0.5)]
qsave(cons.filt.gr, file="metadata/cons.filt.gr.qs", nthreads = cores)
```

```{r Peak plot from conservation data}
DefaultAssay(rV2.data) <- "peaks"
cons.tr <- PeakPlot(rV2.data, peaks = cons.gr.reduced, region=f2.range, color="darkgreen")
cons.tr$labels$y <- "Cons."
```

```{r Annotation track}
gene_track <- AnnotationPlot(
  object = rV2.data,
  region = f2.range
)
```

```{r Linkpeaks track}
links <- fetchGRangesLinks(paste(db.path,dbname.rV2,sep=""), zscore_threshold = 2, pvalue_threshold = 0.05, coordinate_filter=GRangesToString(f2.range),target.gene_name="Tal1")

# Update fetched links to the rV2.data object
Links(rV2.data) <- links

link_track <- LinkPlot(
  object = rV2.data,
  region = f2.range
)
```

```{r}
features.by.region <- as.factor(case_when(all.features.gr %over% StringToGRanges(Links(rV2.data)$peak) ~ "Linked",
                     !all.features.gr %over% StringToGRanges(Links(rV2.data)$peak) ~ "Not-linked"))

rV2.data[["peaks"]] <- AddMetaData(rV2.data[["peaks"]], features.by.region, "Region")
```

```{r Peak track}
peak_track <- PeakPlot(object = rV2.data, region=f2.range,group.by = "Region")
peak_track$labels$y <- "Feat."
```

```{r Tal1 CT}
Tal1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Tal1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.tal1 <- PeakPlot(rV2.data, peaks = Tal1.ct, region=f2.range, color="darkred")
ct.tal1$labels$y <- "C&T Tal1"
```

```{r Gata2 CT}
gata2.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Gata2.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.gata2 <- PeakPlot(rV2.data, peaks = gata2.ct, region=f2.range, color="darkred")
ct.gata2$labels$y <- "C&T Gata2"
```

```{r Gata3 CT}
Gata3.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Gata3.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.gata3 <- PeakPlot(rV2.data, peaks = Gata3.ct, region=f2.range, color="darkred")
ct.gata3$labels$y <- "C&T Gata3"
```

```{r Vsx2 CT}
Vsx2.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Vsx2.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.vsx2 <- PeakPlot(rV2.data, peaks = Vsx2.ct, region=f2.range, color="darkred")
ct.vsx2$labels$y <- "C&T Gata3"
```

```{r Ebf1 CT}
Ebf1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_130824/03_peak_calling/05_consensus_peaks/E12R1_Ebf1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.ebf1 <- PeakPlot(rV2.data, peaks = Ebf1.ct, region=f2.range, color="darkred")
ct.ebf1$labels$y <- "C&T Ebf1"
```

```{r Insm1 CT}
Insm1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_130824/03_peak_calling/05_consensus_peaks/E12R1_Insm1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.insm1 <- PeakPlot(rV2.data, peaks = Insm1.ct, region=f2.range, color="darkred")
ct.insm1$labels$y <- "C&T Ebf1"
```

```{r Expression plot}
expression_plot_data <- ExpressionPlot(object = rV2.data, features=convert_feature_identity(rV2.data, "RNA", c(gene.of.interest,"Pdzk1ip1")), assay="RNA", group.by="rv2.lineage")# & plot_annotation(c(gene.of.interest,"Pdzk1ip1"))
```


```{r Coverage track}
DefaultAssay(rV2.data) <- "peaks"
coverage_track <- Signac::CoveragePlot(rV2.data, 
                  region = f2.range, 
                  annotation = F,
                  peaks = F,
                  links = F,
                  group.by = "rv2.lineage", 
                  downsample.rate = 1, 
                  features = NULL, 
                  expression.assay = "RNA")
```

```{r}
plot_loc <- "~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/"
plot_name <- paste("Figure2_",gene.of.interest,".pdf",sep="")

combined.p <- CombineTracks(
  plotlist = list(coverage_track, gene_track, link_track,peak_track,cons.tr,ct.tal1,ct.gata2,ct.gata3,ct.vsx2,ct.ebf1,ct.insm1),
  expression.plot = expression_plot_data,
  heights = c(.5,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05),
  widths = c(10,5)
) + patchwork::plot_layout(guides = "collect") & theme(legend.direction = 'horizontal')

ggsave(filename = plot_name,
         plot = combined.p,
         path = plot_loc,
         device = "pdf",
         width = 15,
         height = 18,
         units = "in")

```

# Gata2 region plot

```{r Set gene regions}
gene.of.interest <- "Gata2"
f1.range <- range(Annotation(rV2.data)[Annotation(rV2.data)$gene_name %in% gene.of.interest], ignore.strand = TRUE)
f2.range <- f1.range+50000
```

```{r Read and subset conservation data, eval=FALSE}
cons.gr <- import.bw(con="../metadata/mm10.60way.phastCons.bw",as="GRanges")
cons.filt.gr <- cons.gr[(elementMetadata(cons.gr)[, "score"]>=0.5)]
qsave(cons.filt.gr, file="metadata/cons.filt.gr.qs", nthreads = cores)
```

```{r Peak plot from conservation data}
DefaultAssay(rV2.data) <- "peaks"
cons.tr <- PeakPlot(rV2.data, peaks = cons.gr.reduced, region=f2.range, color="darkgreen")
cons.tr$labels$y <- "Cons."
```

```{r Annotation track}
gene_track <- AnnotationPlot(
  object = rV2.data,
  region = f2.range
)
```

```{r Linkpeaks track}
links <- fetchGRangesLinks(paste(db.path,dbname.rV2,sep=""), zscore_threshold = 2, pvalue_threshold = 0.05, coordinate_filter=GRangesToString(f2.range),target.gene_name="Gata2")

# Update fetched links to the rV2.data object
Links(rV2.data) <- links

link_track <- LinkPlot(
  object = rV2.data,
  region = f2.range
)
```

```{r}
features.by.region <- as.factor(case_when(all.features.gr %over% StringToGRanges(Links(rV2.data)$peak) ~ "Linked",
                     !all.features.gr %over% StringToGRanges(Links(rV2.data)$peak) ~ "Not-linked"))

rV2.data[["peaks"]] <- AddMetaData(rV2.data[["peaks"]], features.by.region, "Region")
```

```{r Peak track}
peak_track <- PeakPlot(object = rV2.data, region=f2.range,group.by = "Region")
peak_track$labels$y <- "Feat."
```

```{r Tal1 CT}
Tal1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Tal1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.tal1 <- PeakPlot(rV2.data, peaks = Tal1.ct, region=f2.range, color="darkred")
ct.tal1$labels$y <- "C&T Tal1"
```

```{r Gata2 CT}
gata2.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Gata2.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.gata2 <- PeakPlot(rV2.data, peaks = gata2.ct, region=f2.range, color="darkred")
ct.gata2$labels$y <- "C&T Gata2"
```

```{r Gata3 CT}
Gata3.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Gata3.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.gata3 <- PeakPlot(rV2.data, peaks = Gata3.ct, region=f2.range, color="darkred")
ct.gata3$labels$y <- "C&T Gata3"
```

```{r Vsx2 CT}
Vsx2.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Vsx2.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.vsx2 <- PeakPlot(rV2.data, peaks = Vsx2.ct, region=f2.range, color="darkred")
ct.vsx2$labels$y <- "C&T Gata3"
```

```{r Ebf1 CT}
Ebf1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_130824/03_peak_calling/05_consensus_peaks/E12R1_Ebf1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.ebf1 <- PeakPlot(rV2.data, peaks = Ebf1.ct, region=f2.range, color="darkred")
ct.ebf1$labels$y <- "C&T Ebf1"
```

```{r Insm1 CT}
Insm1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_130824/03_peak_calling/05_consensus_peaks/E12R1_Insm1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.insm1 <- PeakPlot(rV2.data, peaks = Insm1.ct, region=f2.range, color="darkred")
ct.insm1$labels$y <- "C&T Ebf1"
```


```{r Expression plot}
expression_plot_data <- ExpressionPlot(object = rV2.data, features=convert_feature_identity(rV2.data, "RNA", c(gene.of.interest)), assay="RNA", group.by="rv2.lineage")# & plot_annotation(c(gene.of.interest,"Pdzk1ip1"))
```


```{r Coverage track}
DefaultAssay(rV2.data) <- "peaks"
coverage_track <- CoveragePlot(rV2.data, 
                  region = f2.range, 
                  annotation = F,
                  peaks = F,
                  links = F,
                  group.by = "rv2.lineage", 
                  downsample.rate = 1, 
                  features = NULL, 
                  expression.assay = "RNA")
```

```{r}
plot_loc <- "~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/"
plot_name <- paste("Figure2_",gene.of.interest,".pdf",sep="")

combined.p <- CombineTracks(
  plotlist = list(coverage_track, gene_track, link_track,peak_track,cons.tr,ct.tal1,ct.gata2,ct.gata3,ct.vsx2,ct.ebf1,ct.insm1),
  expression.plot = expression_plot_data,
  heights = c(.5,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05),
  widths = c(10,5)
) + patchwork::plot_layout(guides = "collect") & theme(legend.direction = 'horizontal')

ggsave(filename = plot_name,
         plot = combined.p,
         path = plot_loc,
         device = "pdf",
         width = 15,
         height = 18,
         units = "in")

```

# Gata3 region plot

```{r Set gene regions}
gene.of.interest <- "Gata3"
f1.range <- range(Annotation(rV2.data)[Annotation(rV2.data)$gene_name %in% gene.of.interest], ignore.strand = TRUE)
f2.range <- f1.range+50000
```

```{r Read and subset conservation data, eval=FALSE}
cons.gr <- import.bw(con="../metadata/mm10.60way.phastCons.bw",as="GRanges")
cons.filt.gr <- cons.gr[(elementMetadata(cons.gr)[, "score"]>=0.5)]
qsave(cons.filt.gr, file="metadata/cons.filt.gr.qs", nthreads = cores)
```

```{r Peak plot from conservation data}
DefaultAssay(rV2.data) <- "peaks"
cons.tr <- PeakPlot(rV2.data, peaks = cons.gr.reduced, region=f2.range, color="darkgreen")
cons.tr$labels$y <- "Cons."
```

```{r Annotation track}
gene_track <- AnnotationPlot(
  object = rV2.data,
  region = f2.range
)
```

```{r Linkpeaks track}
links <- fetchGRangesLinks(paste(db.path,dbname.rV2,sep=""), zscore_threshold = 2, pvalue_threshold = 0.05, coordinate_filter=GRangesToString(f2.range),target.gene_name="Gata3")

# Update fetched links to the rV2.data object
Links(rV2.data) <- links

link_track <- LinkPlot(
  object = rV2.data,
  region = f2.range
)
```

```{r}
features.by.region <- as.factor(case_when(all.features.gr %over% StringToGRanges(Links(rV2.data)$peak) ~ "Linked",
                     !all.features.gr %over% StringToGRanges(Links(rV2.data)$peak) ~ "Not-linked"))

rV2.data[["peaks"]] <- AddMetaData(rV2.data[["peaks"]], features.by.region, "Region")
```

```{r Peak track}
peak_track <- PeakPlot(object = rV2.data, region=f2.range,group.by = "Region")
peak_track$labels$y <- "Feat."
```


```{r Tal1 CT}
Tal1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Tal1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.tal1 <- PeakPlot(rV2.data, peaks = Tal1.ct, region=f2.range, color="darkred")
ct.tal1$labels$y <- "C&T Tal1"
```

```{r Gata2 CT}
gata2.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Gata2.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.gata2 <- PeakPlot(rV2.data, peaks = gata2.ct, region=f2.range, color="darkred")
ct.gata2$labels$y <- "C&T Gata2"
```

```{r Gata3 CT}
Gata3.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Gata3.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.gata3 <- PeakPlot(rV2.data, peaks = Gata3.ct, region=f2.range, color="darkred")
ct.gata3$labels$y <- "C&T Gata3"
```

```{r Vsx2 CT}
Vsx2.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Vsx2.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.vsx2 <- PeakPlot(rV2.data, peaks = Vsx2.ct, region=f2.range, color="darkred")
ct.vsx2$labels$y <- "C&T Gata3"
```

```{r Ebf1 CT}
Ebf1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_130824/03_peak_calling/05_consensus_peaks/E12R1_Ebf1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.ebf1 <- PeakPlot(rV2.data, peaks = Ebf1.ct, region=f2.range, color="darkred")
ct.ebf1$labels$y <- "C&T Ebf1"
```

```{r Insm1 CT}
Insm1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_130824/03_peak_calling/05_consensus_peaks/E12R1_Insm1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.insm1 <- PeakPlot(rV2.data, peaks = Insm1.ct, region=f2.range, color="darkred")
ct.insm1$labels$y <- "C&T Ebf1"
```



```{r Expression plot}
expression_plot_data <- ExpressionPlot(object = rV2.data, features=convert_feature_identity(rV2.data, "RNA", c(gene.of.interest)), assay="RNA", group.by="rv2.lineage")# & plot_annotation(c(gene.of.interest,"Pdzk1ip1"))
```


```{r Coverage track}
DefaultAssay(rV2.data) <- "peaks"
coverage_track <- CoveragePlot(rV2.data, 
                  region = f2.range, 
                  annotation = F,
                  peaks = F,
                  links = F,
                  group.by = "rv2.lineage", 
                  downsample.rate = 1, 
                  features = NULL, 
                  expression.assay = "RNA")
```

```{r}
plot_loc <- "~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/"
plot_name <- paste("Figure2_",gene.of.interest,".pdf",sep="")

combined.p <- CombineTracks(
  plotlist = list(coverage_track, gene_track, link_track,peak_track,cons.tr,ct.tal1,ct.gata2,ct.gata3,ct.vsx2,ct.ebf1,ct.insm1),
  expression.plot = expression_plot_data,
  heights = c(.5,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05),
  widths = c(10,5)
) + patchwork::plot_layout(guides = "collect") & theme(legend.direction = 'horizontal')

ggsave(filename = plot_name,
         plot = combined.p,
         path = plot_loc,
         device = "pdf",
         width = 15,
         height = 18,
         units = "in")

```

# Vsx2 region plot

```{r Set gene regions}
gene.of.interest <- "Vsx2"
f1.range <- range(Annotation(rV2.data)[Annotation(rV2.data)$gene_name %in% gene.of.interest], ignore.strand = TRUE)
f2.range <- f1.range+50000
```

```{r Read and subset conservation data, eval=FALSE}
cons.gr <- import.bw(con="../metadata/mm10.60way.phastCons.bw",as="GRanges")
cons.filt.gr <- cons.gr[(elementMetadata(cons.gr)[, "score"]>=0.5)]
qsave(cons.filt.gr, file="metadata/cons.filt.gr.qs", nthreads = cores)
```

```{r Peak plot from conservation data}
DefaultAssay(rV2.data) <- "peaks"
cons.tr <- PeakPlot(rV2.data, peaks = cons.gr.reduced, region=f2.range, color="darkgreen")
cons.tr$labels$y <- "Cons."
```

```{r Annotation track}
gene_track <- AnnotationPlot(
  object = rV2.data,
  region = f2.range
)
```

```{r Linkpeaks track}
links <- fetchGRangesLinks(paste(db.path,dbname.rV2,sep=""), zscore_threshold = 2, pvalue_threshold = 0.05, coordinate_filter=GRangesToString(f2.range),target.gene_name="Vsx2")

# Update fetched links to the rV2.data object
Links(rV2.data) <- links

link_track <- LinkPlot(
  object = rV2.data,
  region = f2.range
)
```

```{r}
features.by.region <- as.factor(case_when(all.features.gr %over% StringToGRanges(Links(rV2.data)$peak) ~ "Linked",
                     !all.features.gr %over% StringToGRanges(Links(rV2.data)$peak) ~ "Not-linked"))

rV2.data[["peaks"]] <- AddMetaData(rV2.data[["peaks"]], features.by.region, "Region")
```

```{r Peak track}
peak_track <- PeakPlot(object = rV2.data, region=f2.range,group.by = "Region")
peak_track$labels$y <- "Feat."
```

```{r Tal1 CT}
Tal1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Tal1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.tal1 <- PeakPlot(rV2.data, peaks = Tal1.ct, region=f2.range, color="darkred")
ct.tal1$labels$y <- "C&T Tal1"
```

```{r Gata2 CT}
gata2.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Gata2.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.gata2 <- PeakPlot(rV2.data, peaks = gata2.ct, region=f2.range, color="darkred")
ct.gata2$labels$y <- "C&T Gata2"
```

```{r Gata3 CT}
Gata3.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Gata3.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.gata3 <- PeakPlot(rV2.data, peaks = Gata3.ct, region=f2.range, color="darkred")
ct.gata3$labels$y <- "C&T Gata3"
```

```{r Vsx2 CT}
Vsx2.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_030524/03_peak_calling/05_consensus_peaks/E12R1_Vsx2.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.vsx2 <- PeakPlot(rV2.data, peaks = Vsx2.ct, region=f2.range, color="darkred")
ct.vsx2$labels$y <- "C&T Gata3"
```

```{r Ebf1 CT}
Ebf1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_130824/03_peak_calling/05_consensus_peaks/E12R1_Ebf1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.ebf1 <- PeakPlot(rV2.data, peaks = Ebf1.ct, region=f2.range, color="darkred")
ct.ebf1$labels$y <- "C&T Ebf1"
```

```{r Insm1 CT}
Insm1.ct <- consensus_bed2Granges(bed_file = "/Volumes/MyBookDuo/Data/Cut_Tag/out_130824/03_peak_calling/05_consensus_peaks/E12R1_Insm1.seacr.consensus.peaks.awk.bed")

DefaultAssay(rV2.data) <- "peaks"
ct.insm1 <- PeakPlot(rV2.data, peaks = Insm1.ct, region=f2.range, color="darkred")
ct.insm1$labels$y <- "C&T Ebf1"
```

```{r Expression plot}
expression_plot_data <- ExpressionPlot(object = rV2.data, features=convert_feature_identity(rV2.data, "RNA", c(gene.of.interest)), assay="RNA", group.by="rv2.lineage")# & plot_annotation(c(gene.of.interest,"Pdzk1ip1"))
```


```{r Coverage track}
DefaultAssay(rV2.data) <- "peaks"
coverage_track <- CoveragePlot(rV2.data, 
                  region = f2.range, 
                  annotation = F,
                  peaks = F,
                  links = F,
                  group.by = "rv2.lineage", 
                  downsample.rate = 1, 
                  features = NULL, 
                  expression.assay = "RNA")
```

```{r}
plot_loc <- "~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/"
plot_name <- paste("Figure2_",gene.of.interest,".pdf",sep="")

combined.p <- CombineTracks(
  plotlist = list(coverage_track, gene_track, link_track,peak_track,cons.tr,ct.tal1,ct.gata2,ct.gata3,ct.vsx2,ct.ebf1,ct.insm1),
  expression.plot = expression_plot_data,
  heights = c(.5,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05),
  widths = c(10,5)
) + patchwork::plot_layout(guides = "collect") & theme(legend.direction = 'horizontal')

ggsave(filename = plot_name,
         plot = combined.p,
         path = plot_loc,
         device = "pdf",
         width = 15,
         height = 18,
         units = "in")

```