---
title: "Smoothed heatmaps for Figure 2B-2D, and S3B and S3D"
output: html_notebook
date: '2023-06-20'
---

```{r, include=FALSE, echo=FALSE}
library(Signac)
library(Seurat)
library(dplyr)
library(tidyverse)
library(RColorBrewer)
library(ComplexHeatmap)
library(qs)
library(circlize)
library(magick)
library(GenomicRanges)
library(viridis)
source("../../AuxCode/AuxFunctions.R")
```

Continue here after VIA pseudotime (associated jupyter notebook)

```{r}
rV2.data <- qread("../scATAC_data/nmm_rV2_subset_relabeled_031023_links.qs",nthreads = 6)
via.pseudot <- read.csv("../scATAC_data/seurat_data/rv2_via_pseudotime_110522.csv")
gene_name2id <- qread("gene_name2id.qs")
```

```{r}
via.pseudot.v <- via.pseudot$pseudotime
names(via.pseudot.v) <- via.pseudot$barcode
rV2.data$VIA_pseudotime <- via.pseudot.v
```

```{r}
linkage.p.val.thr <- 0.05
```

# Gata2

```{r Set genes and regions Gata2}
covariate.genes <- c("Gata2","Vsx2","Gad1","Slc17a6")
gene.of.interest <- covariate.genes[1]
# f1.range <- range(Annotation(rV2.data)[Annotation(rV2.data)$gene_name %in% gene.of.interest], ignore.strand = TRUE)
# f2.range <- f1.range+50000
```

```{r}
plots.1 <- plotSmoothedAccessibility_v2(dataset=rV2.data,covariate.genes.to.plot=covariate.genes, features.df=filter(result.Gata2,pvalue<linkage.p.val.thr), drop.non.linked=FALSE, GABA = TRUE,gene_id2name=gene_id2name, gene_name2id=gene_name2id, gene.feat.name=gene.of.interest,unify_expression_scale = TRUE, max_accessibility_value = 3,assign_above_max_to_white = TRUE)

plots.2 <- plotSmoothedAccessibility_v2(dataset=rV2.data,covariate.genes.to.plot=covariate.genes, features.df=filter(result.Gata2,pvalue<linkage.p.val.thr), drop.non.linked=FALSE, GABA = FALSE,gene_id2name=gene_id2name, gene_name2id=gene_name2id, gene.feat.name=gene.of.interest,unify_expression_scale = TRUE, max_accessibility_value = 3,assign_above_max_to_white = TRUE)
```

```{r}
pdf(file = str_interp("~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/GA_${gene.of.interest}_smoothed_heatmap.pdf"), width = 28, height = 24)
draw(plots.1)
dev.off()

pdf(file = str_interp("~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/GL_${gene.of.interest}_smoothed_heatmap.pdf"), width = 28, height = 24)
draw(plots.2)
dev.off()
```
# Vsx2

```{r Set genes and regions Vsx2}
covariate.genes <- c("Vsx2","Tal1","Gad1","Slc17a6")
gene.of.interest <- covariate.genes[1]

```

```{r}
plots.1 <- plotSmoothedAccessibility_v2(dataset=rV2.data,covariate.genes.to.plot=covariate.genes, features.df=filter(result.Vsx2,pvalue<linkage.p.val.thr), drop.non.linked=FALSE, GABA = TRUE,gene_id2name=gene_id2name, gene_name2id=gene_name2id, gene.feat.name=gene.of.interest,unify_expression_scale = TRUE, max_accessibility_value = 3,assign_above_max_to_white = TRUE)

plots.2 <- plotSmoothedAccessibility_v2(dataset=rV2.data,covariate.genes.to.plot=covariate.genes, features.df=filter(result.Vsx2,pvalue<linkage.p.val.thr), drop.non.linked=FALSE, GABA = FALSE,gene_id2name=gene_id2name, gene_name2id=gene_name2id, gene.feat.name=gene.of.interest,unify_expression_scale = TRUE, max_accessibility_value = 3,assign_above_max_to_white = TRUE)
```

```{r}
pdf(file = str_interp("~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/GA_${gene.of.interest}_smoothed_heatmap.pdf"), width = 28, height = 24)
draw(plots.1)
dev.off()

pdf(file = str_interp("~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/GL_${gene.of.interest}_smoothed_heatmap.pdf"), width = 28, height = 24)
draw(plots.2)
dev.off()
```

# Tal1

```{r Set genes and regions Tal1}
covariate.genes <- c("Tal1","Gata2","Gad1","Slc17a6")
gene.of.interest <- covariate.genes[1]
```

```{r}
plots.1 <- plotSmoothedAccessibility_v2(dataset=rV2.data,covariate.genes.to.plot=covariate.genes, features.df=filter(result.Tal1,pvalue<linkage.p.val.thr), drop.non.linked=FALSE, GABA = TRUE,gene_id2name=gene_id2name, gene_name2id=gene_name2id, gene.feat.name=gene.of.interest,unify_expression_scale = TRUE, max_accessibility_value = 3,assign_above_max_to_white = TRUE)

plots.2 <- plotSmoothedAccessibility_v2(dataset=rV2.data,covariate.genes.to.plot=covariate.genes, features.df=filter(result.Tal1,pvalue<linkage.p.val.thr), drop.non.linked=FALSE, GABA = FALSE,gene_id2name=gene_id2name, gene_name2id=gene_name2id, gene.feat.name=gene.of.interest,unify_expression_scale = TRUE, max_accessibility_value = 3,assign_above_max_to_white = TRUE)
```

```{r}
pdf(file = str_interp("~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/GA_${gene.of.interest}_smoothed_heatmap.pdf"), width = 28, height = 24)
draw(plots.1)
dev.off()

pdf(file = str_interp("~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/GL_${gene.of.interest}_smoothed_heatmap.pdf"), width = 28, height = 24)
draw(plots.2)
dev.off()
```

# Gata3

```{r Set genes and regions Gata3}
covariate.genes <- c("Gata3","Tal1","Gad1","Slc17a6")
gene.of.interest <- covariate.genes[1]
```

```{r}
plots.1 <- plotSmoothedAccessibility_v2(dataset=rV2.data,covariate.genes.to.plot=covariate.genes, features.df=filter(result.Gata3,pvalue<linkage.p.val.thr), drop.non.linked=FALSE, GABA = TRUE,gene_id2name=gene_id2name, gene_name2id=gene_name2id, gene.feat.name=gene.of.interest,unify_expression_scale = TRUE, max_accessibility_value = 3,assign_above_max_to_white = TRUE)

plots.2 <- plotSmoothedAccessibility_v2(dataset=rV2.data,covariate.genes.to.plot=covariate.genes, features.df=filter(result.Gata3,pvalue<linkage.p.val.thr), drop.non.linked=FALSE, GABA = FALSE,gene_id2name=gene_id2name, gene_name2id=gene_name2id, gene.feat.name=gene.of.interest,unify_expression_scale = TRUE, max_accessibility_value = 3,assign_above_max_to_white = TRUE)
```

```{r}
pdf(file = str_interp("~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/GA_${gene.of.interest}_smoothed_heatmap.pdf"), width = 28, height = 24)
draw(plots.1)
dev.off()

pdf(file = str_interp("~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig2/GL_${gene.of.interest}_smoothed_heatmap.pdf"), width = 28, height = 24)
draw(plots.2)
dev.off()
```

```{r}
sessionInfo()
```

