---
title: "R Notebook of rV2 manuscript figure 1 plots"
output: html_notebook
---

```{r Packagies}
library(tidyverse)
library(Seurat)
library(Signac)
library(qs)
library(viridis)
source("AuxFunctions.R")
```

```{r Set parameters}
threads <- 6
```

```{r Load data, eval=FALSE, include=FALSE}
rV2.data <- readRDS("../scATAC_data/seurat_data/nmm_rV2_subset_relabeled_110522.Rds")
rV2.pseudotime <- read.csv("../scATAC_data/seurat_data/rv2_via_pseudotime_110522.csv")
```

```{r Add metadata and store as qs object, eval=FALSE, include=FALSE}
rV2.data <- AddMetaData(rV2.data, col.name="pseudotime", metadata = rV2.pseudotime$pseudotime)
qsave(rV2.data, file="../scATAC_data/nmm_rV2_subset_relabeled_110522.qs", nthreads = threads)
```

```{r Load data objects}
rV2.data <- qread("../scATAC_data/nmm_rV2_subset_relabeled_110522.qs", nthreads = threads)
DefaultAssay(rV2.data) <- "peaks"

rV2.barcodes <- readRDS("../scRNA_data/RNAseq/data/e12_rv2_clean_subset_310323.rds")
e.e12.r1 <- qread("../scRNA_data/e.e12_r1_200623.qs", nthreads = threads)

e12.rv2.ss <- subset(e.e12.r1 , cells = rV2.barcodes)
```

```{r Markers for rV2 scRNA clusters}
rV2.markers <- as_tibble(FindAllMarkers(e12.rv2.ss)) %>%  mutate(across(where(is.numeric),round,digits = 3))
rV2.markers$gene_name <- convert_feature_identity(e12.rv2.ss,assay = "RNA", features = rV2.markers$gene, feature.format = "ens")
create_dt(rV2.markers)
```

```{r scRNA UMAP}
pdf("/Users/kilpinen/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig1/scRNA_UMAP_rV2.pdf", width = 8, height = 8)

new.axes <-  ExpandAxes(x=e12.rv2.ss@reductions$umap@cell.embeddings[,1], y=e12.rv2.ss@reductions$umap@cell.embeddings[,2])

DimPlot(e12.rv2.ss, reduction = "umap", label = TRUE) + theme(legend.position = "none") + ylim(new.axes$y.range) + xlim(new.axes$x.range) + theme(axis.text.y = element_text(size=20),axis.text.x = element_text(size=20))

dev.off()
```
```{r Marker gene feature plots scRNA}
for(g in c("Vsx2","Tal1","Nkx6-1","Nes","Gad1","Slc17a6","Ccnb1","Cenpa","Ube2c")){
  pdf(file = paste("/Users/kilpinen/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig1/",g,"_RNA_UMAP.pdf",sep=""), width = 4, height = 4)
  f.p <- PlotRNAFeature(s.data = e12.rv2.ss, feature = g)
  print(f.p)
  dev.off()
}
```

```{r scATAC UMAP}
pdf("/Users/kilpinen/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig1/scATAC_UMAP_rV2.pdf", width = 8, height = 8)

new.axes <-  ExpandAxes(x=rV2.data@reductions$umap@cell.embeddings[,1], y=rV2.data@reductions$umap@cell.embeddings[,2])

DimPlot(rV2.data, reduction = "umap", label = TRUE) + theme(legend.position = "none") + ylim(new.axes$y.range) + xlim(new.axes$x.range) + theme(axis.text.y = element_text(size=20),axis.text.x = element_text(size=20))
dev.off()
```

```{r Marker gene feature plots scATAC}
for(g in c("Vsx2","Tal1","Nkx6-1","Nes","Gad1","Slc17a6","Ccnb1","Cenpa","Ube2c")){
  pdf(file = paste("/Users/kilpinen/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig1/",g,"_ATAC_UMAP.pdf",sep=""), width = 4, height = 4)
  f.p <- PlotRNAFeature(s.data = rV2.data, feature = g)
  print(f.p)
  dev.off()
}
```

```{r scATAC UMAP pseudotime}
pdf("/Users/kilpinen/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/Fig1/scATAC_UMAP_pseudotime.pdf", width = 8, height = 8)

FeaturePlot(rV2.data, features = "pseudotime") + ylim(new.axes$y.range) + xlim(new.axes$x.range) + labs(title="") + scale_color_viridis() + theme(axis.text.y = element_text(size=20),axis.text.x = element_text(size=20))

dev.off()
```

