---
title: "R Notebook for testing GSEA calculations for target genes"
author: Sami Kilpinen
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_notebook:
    code_folding: hide
---

```{r, include=FALSE}
library(tidyverse)
library(Seurat)
library(Signac)
library(qs)
library(readxl)
library(hash)
library(fgsea)
library(DBI)
library(hash)
library(biomaRt)
library(presto)
library(topGO)
source("../../AuxCode/AuxFunctions.R")
```

```{r, include=FALSE}
cores <- 8
con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "~/Workspace/TOBIAS.dr.h12_210324.sqlite")
options(timeout = 30000)
```

```{r, include=FALSE}
plot_loc <- "~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/training/"

rV2.dataset <- qread("../scATAC_data/nmm_rV2_subset_relabeled_031023_links.qs", nthreads = cores)

rV2.dataset$rv2.lineage_re <- case_when(
  rV2.dataset$rv2.lineage %in% "PRO1" ~ "PRO1_2",
  rV2.dataset$rv2.lineage %in% "PRO2" ~ "PRO1_2",
  rV2.dataset$rv2.lineage %in% "GA1" ~ "GA1_2",
  rV2.dataset$rv2.lineage %in% "GA2" ~ "GA1_2",
  rV2.dataset$rv2.lineage %in% "GA3" ~ "GA3_4",
  rV2.dataset$rv2.lineage %in% "GA4" ~ "GA3_4",
  rV2.dataset$rv2.lineage %in% "GA5" ~ "GA5_6",
  rV2.dataset$rv2.lineage %in% "GA6" ~ "GA5_6",
  rV2.dataset$rv2.lineage %in% "CO1" ~ "CO1_2",
  rV2.dataset$rv2.lineage %in% "CO2" ~ "CO1_2",
  rV2.dataset$rv2.lineage %in% "GL1" ~ "GL1_2",
  rV2.dataset$rv2.lineage %in% "GL2" ~ "GL1_2",
  rV2.dataset$rv2.lineage %in% "GL3" ~ "GL3_4",
  rV2.dataset$rv2.lineage %in% "GL4" ~ "GL3_4",
  rV2.dataset$rv2.lineage %in% "GL5" ~ "GL5",
)


DefaultAssay(rV2.dataset) <- "RNA"

serot.dataset <- qread("../serot/sero_relabeled_201123_links.qs", nthreads = cores)
```

```{r, include=FALSE}
merged.datasets <- merge(rV2.dataset,serot.dataset)

# merged.datasets$merged.groups <- factor(ifelse(is.na(merged.datasets$sero.lineage), merged.datasets$rv2.lineage, merged.datasets$sero.lineage), levels=c("PRO1","PRO2","CO1","CO2","GA1","GA2","GA3","GA4","GA5","GA6","GL1","GL2","GL3","GL4","GL5","SR1","SR2","SR3"))

merged.datasets$merged.groups <- factor(ifelse(is.na(merged.datasets$sero.lineage), merged.datasets$rv2.lineage_re, merged.datasets$sero.lineage), levels=c("PRO1_2","CO1_2","GA1_2","GA3_4","GA5_6","GL1_2","GL3_4","GL5","SR1","SR2","SR3"))

gene_id2name <- hash(rownames(rV2.dataset[['RNA']][[]]),rV2.dataset[['RNA']][[]][,1])
gene_name2id <- hash(rV2.dataset[['RNA']][[]][,1],rownames(rV2.dataset[['RNA']][[]]))
  
DefaultAssay(merged.datasets) <- "RNA"
```

```{r}
mean.fxn <- function (x) 
{
    return(log(x = rowMeans(x = expm1(x = x)) + pseudocount.use, 
        base = base))
}
```


```{r, include=FALSE}
assay.averages <- AverageExpression(rV2.dataset,group.by = "rv2.lineage_re")

# ga.ni <- which(rV2.dataset$rv2.lineage_re == "GA1_2")
# gl.ni <- which(rV2.dataset$rv2.lineage_re == "GL1_2")
# exp.mat <- FetchData(rV2.dataset, vars = rownames(rV2.dataset), slot="data")
# log(colMeans(expm1(exp.mat[ga.ni,]))+1,base=2)["ENSMUSG00000028717"]
# 
# log(colMeans(expm1(exp.mat[gl.ni,]))+1,base=2)["ENSMUSG00000028717"]
# 
# DEG.res$GA1_2_exp_avg["ENSMUSG00000028717"]

# ENSMUSG00000028717 
#           5.214443 

#min.filter <- (assay.averages$RNA[,"GA1_2"]>0.1 | assay.averages$RNA[,"GA1_2"]==0) & (assay.averages$RNA[,"GL1_2"]>0.1 | assay.averages$RNA[,"GL1_2"]==0)
#log2.GA1_GL1 <- log2(assay.averages$RNA[,"GA1_2"]/assay.averages$RNA[,"GL1_2"])
#log2.GA1_GL1 <- sort(log2.GA1_GL1[is.finite(log2.GA1_GL1)])
Idents(rV2.dataset) <- rV2.dataset$rv2.lineage_re
DEG.res <- FindMarkers(rV2.dataset, ident.1="GA1_2", ident.2 = "GL1_2",logfc.threshold=0, assay = "RNA", slot="data") %>% rownames_to_column(var="ensg_id") %>% as_tibble() %>% filter(p_val_adj<0.05)

DEG.res$GL1_2_exp_avg_log2 <- log(assay.averages$RNA[DEG.res$ensg_id,"GL1_2"]+1,base=2)
DEG.res$GA1_2_exp_avg_log2 <- log(assay.averages$RNA[DEG.res$ensg_id,"GA1_2"]+1, base=2)
DEG.res$GL1_2_exp_avg <- assay.averages$RNA[DEG.res$ensg_id,"GL1_2"]
DEG.res$GA1_2_exp_avg <- assay.averages$RNA[DEG.res$ensg_id,"GA1_2"]
DEG.res$gene_name <- sapply(DEG.res$ensg_id,function(ensg_id){hash::values(gene_id2name[ensg_id])})
DEG.res <- DEG.res %>% mutate(across(where(is.numeric), \(x) round(x, digits = 8))) %>% arrange(avg_log2FC)

DEG.res.GSEA <- DEG.res$avg_log2FC
names(DEG.res.GSEA) <- DEG.res$gene_name

# DEG.res$avg_log2FC <- filter(DEG.res, p_val_adj<0.05) %>% pull(avg_log2FC)
# names(DEG.res$avg_log2FC) <- filter(DEG.res, p_val_adj<0.05) %>% pull(ensg_id)
# names(DEG.res$avg_log2FC) <- sapply(names(DEG.res$avg_log2FC),function(ensg_id){hash::values(gene_id2name[ensg_id])})
```

```{r}
upper.thr <- .75
lower.thr <- .25

upper.limit <- quantile(DEG.res$avg_log2FC,upper.thr)
upper.pos <- which.min(abs(DEG.res$avg_log2FC-upper.limit))

lower.limit <- quantile(DEG.res$avg_log2FC,lower.thr)
lower.pos <- which.min(abs(DEG.res$avg_log2FC-lower.limit))

mid.thr.width <- .25
width.around.zero <- round(nrow(DEG.res)*(mid.thr.width/2), digits = 0)
zero.index <- which.min(abs(DEG.res$avg_log2FC))

mid.lower.index <- zero.index-width.around.zero
mid.upper.index <- zero.index+width.around.zero

allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])


```


# GSEA results {.tabset}

## With C&T included in conditions

```{r}
TF_name<-"Tal1"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, CT_data as ct, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND ct.target_gene_name='",TF_name,"' AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND ct.feature=tb.features AND tb.TFBS_name='TAL1.H12CORE.0.P.B_TAL1.H12CORE.0.P.B' AND tb.mean_cons>0.5;",sep="")
targets.Tal1 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Tal1$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Tal1$gene_name))

TF_name<-"Gata2"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name  FROM links as li, tobias as tb, CT_data as ct, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND ct.target_gene_name='",TF_name,"' AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND ct.feature=tb.features AND tb.mean_cons>0.5;",sep="") 
targets.Gata2 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Gata2$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Gata2$gene_name))

TF_name<-"Gata3"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, CT_data as ct, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND ct.target_gene_name='",TF_name,"' AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND ct.feature=tb.features AND tb.mean_cons>0.5;",sep="") 
targets.Gata3 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Gata3$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Gata3$gene_name))

TF_name<-"Vsx2"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, CT_data as ct, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND ct.target_gene_name='",TF_name,"' AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND ct.feature=tb.features AND tb.mean_cons>0.5;",sep="")
targets.Vsx2 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Vsx2$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Vsx2$gene_name))

TF_name<-"Sox4"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, CT_data as ct, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND ct.target_gene_name='",TF_name,"' AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND ct.feature=tb.features AND tb.mean_cons>0.5;",sep="") 
targets.Sox4 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Sox4$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Sox4$gene_name))

geneSets <- list(targets.Tal1=targets.Tal1$gene_name, targets.Gata2=targets.Gata2$gene_name, targets.Gata3=targets.Gata3$gene_name,targets.Sox4=targets.Sox4$gene_name, targets.Vsx2=targets.Vsx2$gene_name)

results <- fgsea(pathways = geneSets, 
                 stats = DEG.res.GSEA, 
                 minSize = 5,  # Minimum size of a gene set to be considered
                 maxSize = 5000) # Maximum size of a gene set to be considered
print("Summary")
results <- results %>% mutate(across(where(is.numeric), \(x) round(x, digits=3)))
create_dt(results)
```

## Without C&T in conditions

```{r}
TF_name<-"Tal1"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1)  AND tb.TFBS_name='TAL1.H12CORE.0.P.B_TAL1.H12CORE.0.P.B' AND tb.mean_cons>0.5;",sep="")
targets.Tal1 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Tal1$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Tal1$gene_name))

TF_name<-"Gata2"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name  FROM links as li, tobias as tb, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND tb.mean_cons>0.5;",sep="") 
targets.Gata2 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Gata2$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Gata2$gene_name))

TF_name<-"Gata3"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1)  AND tb.mean_cons>0.5;",sep="") 
targets.Gata3 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Gata3$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Gata3$gene_name))

TF_name<-"Vsx2"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND tb.mean_cons>0.5;",sep="")
targets.Vsx2 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Vsx2$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Vsx2$gene_name))

TF_name<-"Sox4"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND tb.mean_cons>0.5;",sep="") 
targets.Sox4 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Sox4$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Sox4$gene_name))

TF_name<-"Klf17"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND tb.mean_cons>0.5;",sep="") 
targets.Klf17 <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Klf17$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Klf17$gene_name))

TF_name<-"Myc"
print(TF_name)
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND li.zscore>2 AND li.pvalue<0.001 AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND tb.mean_cons>0.5;",sep="") 
targets.Myc <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
plotEnrichment(targets.Myc$gene_name, DEG.res.GSEA) + ggtitle(paste(TF_name,"target enrichments in GA/GL DEG")) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002)+ geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002)+ geom_rect(aes(xmin=upper.pos,xmax=nrow(DEG.res),ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
create_dt(DEG.res %>% filter(gene_name %in% targets.Myc$gene_name))

geneSets <- list(targets.Tal1=targets.Tal1$gene_name, targets.Gata2=targets.Gata2$gene_name, targets.Gata3=targets.Gata3$gene_name,targets.Sox4=targets.Sox4$gene_name, targets.Vsx2=targets.Vsx2$gene_name,targets.Klf17=targets.Klf17$gene_name,targets.Myc=targets.Myc$gene_name)

print("Summary")
results <- fgsea(pathways = geneSets, 
                 stats = DEG.res.GSEA, 
                 minSize = 5,  # Minimum size of a gene set to be considered
                 maxSize = 5000) # Maximum size of a gene set to be considered
results <- results %>% mutate(across(where(is.numeric), \(x) round(x, digits=3)))
create_dt(results)
```

```{r Connect Ensembl to fetch GO and set thresholds}
# Connect to the Ensembl database
ensembl <- useMart("ENSEMBL_MART_ENSEMBL", dataset = "mmusculus_gene_ensembl", host="https://nov2020.archive.ensembl.org")
gene_names_with_go <- getBM(attributes = c('external_gene_name', 'go_id'),
                       filters = 'with_go', # This filter is to only fetch genes with GO IDs
                       values = TRUE,
                       mart = ensembl)
# Split the data.frame into a list where each element is a character vector of GO IDs,
# and the names of the list elements are the Ensembl gene IDs
geneID2GO <- split(gene_names_with_go$go_id, gene_names_with_go$external_gene_name)
GO2geneID <- split(gene_names_with_go$external_gene_name,gene_names_with_go$go_id)
# Optionally, you can remove genes with no GO IDs if any exist
geneID2GO <- geneID2GO[sapply(geneID2GO, length) > 0]
```


# GO enrichments 25-25-25 among target genes (C&T overlap incl.) {.tabset}

## Tal1 targets

### Up in GA

```{r}
geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Tal1, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```
### Neutral

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Tal1, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```

### Up in GL

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Tal1, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```

## Gata2 targets

### Up in GA

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata2, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```
### Neutral

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata2, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```

### Up in GL

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata2, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```


## Gata3 targets

### Up in GA

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata3, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```
### Neutral

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata3, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```

### Up in GL

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata3, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```



## Vsx2 targets

### Up in GA

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Vsx2, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```

### Neutral

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Vsx2, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```

### Up in GL

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Vsx2, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```


## Sox4 targets

### Up in GA

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Sox4, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```
### Neutral

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Sox4, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```

### Up in GL

```{r}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])

geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Sox4, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0))
names(geneList.fac) <- allGenes.list

sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP",
allGenes = geneList.fac,
nodeSize = 5,
annot = annFUN.gene2GO, gene2GO = geneID2GO)

resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher")
allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25))

genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){
  tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata))
  return(paste(tmp.genes, collapse = ", "))
  })

allRes$genes.in.classes <- genes.in.classes

create_dt(allRes)
sigGenes(sampleGOdata)
```


