---
title: "R Notebook for selector gene target analysis"
author: Sami Kilpinen
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_notebook:
    code_folding: hide
---

```{r Packages, include=FALSE}
library(tidyverse)
library(Seurat)
library(Signac)
library(qs)
library(readxl)
library(hash)
library(fgsea)
library(DBI)
library(hash)
#library(biomaRt)
library(presto)
library(purrr)
library(circlize)
library(ComplexHeatmap)
library(topGO)
library(dplyr)
source("../../AuxCode/AuxFunctions.R")
```

```{r Functions}
mean.fxn <- function (x,pseudocount.use=1, base=2)
{
    return(log(x = rowMeans(x = expm1(x = x)) + pseudocount.use,
        base = base))
}

getTargets <- function(TF_name, CT, Cons, ft){
  if (!CT & ft){
targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND ABS(li.zscore)>2 AND li.pvalue<0.001 AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND tb.mean_cons>0.5;",sep="")
  } else if (!Cons & CT & ft){
  targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, CT_data as ct, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND ABS(li.zscore)>2 AND li.pvalue<0.001 AND ct.target_gene_name='",TF_name,"' AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND ct.feature=tb.features;",sep="")
  } else if (Cons & CT & ft){
  targetQuery <- paste("SELECT gm.gene_name FROM links as li, tobias as tb, CT_data as ct, gene_metadata as gm WHERE gm.ensg_id=li.ensg_id AND tb.features=li.feature AND tb.TF_gene_name='",toupper(TF_name),"' AND ABS(li.zscore)>2 AND li.pvalue<0.001 AND ct.target_gene_name='",TF_name,"' AND (tb.GA1_2_bound=1 OR tb.GL1_2_bound=1) AND ct.feature=tb.features AND tb.mean_cons>0.5;",sep="")
  } else if (!ft) {
      targetQuery <- paste("SELECT gm.gene_name FROM links as li, CT_data as ct, gene_metadata as gm, tobias as tb WHERE gm.ensg_id=li.ensg_id AND ct.feature=li.feature AND ABS(li.zscore)>2 AND li.pvalue<0.001 AND ct.target_gene_name='",TF_name,"' AND tb.mean_cons>0.5 AND tb.features=li.feature;",sep="")
  } else {stop("No such combo supported")}
targets <- as_tibble(dbGetQuery(con, targetQuery)) %>% distinct()
return(pull(targets,gene_name))
}

do.GSEA <- function(targets,DEG.res,TF.name, comp.title){
  lower.thr <- .25
  upper.thr <- .75
  
  upper.limit <- quantile(DEG.res$avg_log2FC,upper.thr)
  upper.pos <- which.min(abs(DEG.res$avg_log2FC-upper.limit))
  
  lower.limit <- quantile(DEG.res$avg_log2FC,lower.thr)
  lower.pos <- which.min(abs(DEG.res$avg_log2FC-lower.limit))
  
  mid.thr.width <- .25
  width.around.zero <- round(nrow(DEG.res)*(mid.thr.width/2), digits = 0)
  zero.index <- which.min(abs(DEG.res$avg_log2FC))
  
  mid.lower.index <- zero.index-width.around.zero
  mid.upper.index <- zero.index+width.around.zero
  
  xmax.right <- nrow(DEG.res)
  
  DEG.res.GSEA <- DEG.res$avg_log2FC
  names(DEG.res.GSEA) <- DEG.res$gene_name
  p1 <- plotEnrichment(targets, DEG.res.GSEA) + ggtitle(paste(TF.name,"target enrichments in", comp.title)) + geom_rect(aes(xmin=0,xmax=lower.pos,ymin=-0.05,ymax=0.05), fill="blue", alpha=0.002) + geom_rect(aes(xmin=mid.lower.index,xmax=mid.upper.index,ymin=-0.05,ymax=0.05), fill="green", alpha=0.002) + geom_rect(aes(xmin=upper.pos,xmax=xmax.right,ymin=-0.05,ymax=0.05), fill="red", alpha=0.002)
  d1 <- DEG.res %>% dplyr::filter(gene_name %in% targets)
  return(list(p1=p1,d1=d1))
}
```

```{r Setting variables, include=FALSE}
cores <- 6
con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "~/Workspace/TOBIAS.dr.h12_230424.sqlite")
options(timeout = 30000)

plot_loc <- "~/OneDrive - University of Helsinki/E12R1 project/Manuscript I - Regulation of Tal1 dependent rV2 lineage bifurcation/Figures/plots/training/"
```

# Target counts {.tabset}

## Without C&T False and Cons True - Set1

```{r Set1}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2","Sox4","Klf17","Myc")
targetGenes.set.1 <- lapply(TF_names,getTargets,CT=FALSE, Cons=TRUE)
names(targetGenes.set.1) <- TF_names
sapply(targetGenes.set.1,length)
```

## With C&T True and Cons False - Set 2
```{r Set2}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2","Sox4","Klf17","Myc")
targetGenes.set.2 <- lapply(TF_names,getTargets,CT=TRUE, Cons=FALSE)
names(targetGenes.set.2) <- TF_names
sapply(targetGenes.set.2,length)
```

## With C&T True and Cons True - Set3

```{r Set3}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2","Sox4","Klf17","Myc")
targetGenes.set.3 <- lapply(TF_names,getTargets,CT=TRUE, Cons=TRUE)
names(targetGenes.set.3) <- TF_names
sapply(targetGenes.set.3,length)
```

## With C&T True and Cons False ft True - Set4

```{r Set4}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2","Sox4","Klf17","Myc")
targetGenes.set.4 <- lapply(TF_names,getTargets,CT=TRUE, Cons=TRUE, ft=FALSE)
names(targetGenes.set.4) <- TF_names
sapply(targetGenes.set.4,length)
```


## Combined

```{r}
combined.target.counts <- rbind(sapply(targetGenes.set.1,length),sapply(targetGenes.set.2,length),sapply(targetGenes.set.3,length),sapply(targetGenes.set.4,length))

rownames(combined.target.counts) <- c("CT False and Cons True","CT True and Cons False","CT True and Cons True","CT True and Cons True and FT False")
create_dt(combined.target.counts)
```

# GSEA analysis of target genes {.tabset}

```{r Reading rV2 data, include=FALSE}
rV2.dataset <- qread("../scATAC_data/nmm_rV2_subset_relabeled_031023_links.qs", nthreads = cores)

rV2.dataset$rv2.lineage_re <- case_when(
  rV2.dataset$rv2.lineage %in% "PRO1" ~ "PRO1_2",
  rV2.dataset$rv2.lineage %in% "PRO2" ~ "PRO1_2",
  rV2.dataset$rv2.lineage %in% "GA1" ~ "GA1_2",
  rV2.dataset$rv2.lineage %in% "GA2" ~ "GA1_2",
  rV2.dataset$rv2.lineage %in% "GA3" ~ "GA3_4",
  rV2.dataset$rv2.lineage %in% "GA4" ~ "GA3_4",
  rV2.dataset$rv2.lineage %in% "GA5" ~ "GA5_6",
  rV2.dataset$rv2.lineage %in% "GA6" ~ "GA5_6",
  rV2.dataset$rv2.lineage %in% "CO1" ~ "CO1_2",
  rV2.dataset$rv2.lineage %in% "CO2" ~ "CO1_2",
  rV2.dataset$rv2.lineage %in% "GL1" ~ "GL1_2",
  rV2.dataset$rv2.lineage %in% "GL2" ~ "GL1_2",
  rV2.dataset$rv2.lineage %in% "GL3" ~ "GL3_4",
  rV2.dataset$rv2.lineage %in% "GL4" ~ "GL3_4",
  rV2.dataset$rv2.lineage %in% "GL5" ~ "GL5",
)

DefaultAssay(rV2.dataset) <- "RNA"

gene_id2name <- hash(rownames(rV2.dataset[['RNA']][[]]),rV2.dataset[['RNA']][[]][,1])
gene_name2id <- hash(rV2.dataset[['RNA']][[]][,1],rownames(rV2.dataset[['RNA']][[]]))
```

```{r reading Serot data and merging}
serot.dataset <- qread("../serot/sero_relabeled_201123_links.qs", nthreads = cores)
merged.datasets <- merge(rV2.dataset,serot.dataset)

merged.datasets$merged.groups <- factor(ifelse(is.na(merged.datasets$sero.lineage), merged.datasets$rv2.lineage_re, merged.datasets$sero.lineage), levels=c("PRO1_2","CO1_2","GA1_2","GA3_4","GA5_6","GL1_2","GL3_4","GL5","SR1","SR2","SR3"))

merged.datasets$merged.groups <- fct_collapse(merged.datasets$merged.groups, SR2_3 = c("SR2", "SR3"))

gene_id2name <- hash(rownames(rV2.dataset[['RNA']][[]]),rV2.dataset[['RNA']][[]][,1])
gene_name2id <- hash(rV2.dataset[['RNA']][[]][,1],rownames(rV2.dataset[['RNA']][[]]))
  
DefaultAssay(merged.datasets) <- "RNA"
```

```{r Calculating averages and DEG for GA/GL axis, include=FALSE}
assay.averages <- AverageExpression(rV2.dataset,group.by = "rv2.lineage_re")

Idents(rV2.dataset) <- rV2.dataset$rv2.lineage_re
DEG.res <- FindMarkers(rV2.dataset, ident.1="GA1_2", ident.2 = "GL1_2",logfc.threshold=0, assay = "RNA", slot="data", mean.fxn=mean.fxn) %>% rownames_to_column(var="ensg_id") %>% as_tibble() %>% dplyr::filter(p_val_adj<0.01)

colnames(assay.averages$RNA) <- str_replace_all(colnames(assay.averages$RNA), pattern = "-", replacement = "_")

DEG.res$GL1_2_exp_avg_log2 <- log(assay.averages$RNA[DEG.res$ensg_id,"GL1_2"]+1,base=2)
DEG.res$GA1_2_exp_avg_log2 <- log(assay.averages$RNA[DEG.res$ensg_id,"GA1_2"]+1, base=2)
DEG.res$GL1_2_exp_avg <- assay.averages$RNA[DEG.res$ensg_id,"GL1_2"]
DEG.res$GA1_2_exp_avg <- assay.averages$RNA[DEG.res$ensg_id,"GA1_2"]
DEG.res$gene_name <- sapply(DEG.res$ensg_id,function(ensg_id){hash::values(gene_id2name[ensg_id])})
DEG.res <- DEG.res %>% mutate(across(where(is.numeric), \(x) round(x, digits = 8))) %>% arrange(avg_log2FC)

#DEG.res <- filter(DEG.res, (GL1_2_exp_avg>1.2 | GA1_2_exp_avg>1.2) | (abs(avg_log2FC)>2) & (pct.1>.25 & pct.2>.25))

DEG.res.GSEA <- DEG.res$avg_log2FC
names(DEG.res.GSEA) <- DEG.res$gene_name
```

```{r Calculating averages and DEG for GA/Serot axis, include=FALSE}
assay.averages <- AverageExpression(merged.datasets,group.by = "merged.groups")

Idents(merged.datasets) <- merged.datasets$merged.groups
DEG.res.GASR <- FindMarkers(merged.datasets, ident.1="GA1_2", ident.2 = "SR2_3",logfc.threshold=0, assay = "RNA", slot="data", mean.fxn=mean.fxn) %>% rownames_to_column(var="ensg_id") %>% as_tibble() %>% dplyr::filter(p_val_adj<0.01)

colnames(assay.averages$RNA) <- str_replace_all(colnames(assay.averages$RNA), pattern = "-", replacement = "_")

DEG.res.GASR$SR2_3_exp_avg_log2 <- log(assay.averages$RNA[DEG.res.GASR$ensg_id,"SR2_3"]+1,base=2)
DEG.res.GASR$GA1_2_exp_avg_log2 <- log(assay.averages$RNA[DEG.res.GASR$ensg_id,"GA1_2"]+1, base=2)
DEG.res.GASR$SR2_3_exp_avg <- assay.averages$RNA[DEG.res.GASR$ensg_id,"SR2_3"]
DEG.res.GASR$GA1_2_exp_avg <- assay.averages$RNA[DEG.res.GASR$ensg_id,"GA1_2"]
DEG.res.GASR$gene_name <- sapply(DEG.res.GASR$ensg_id,function(ensg_id){hash::values(gene_id2name[ensg_id])})
DEG.res.GASR <- DEG.res.GASR %>% mutate(across(where(is.numeric), \(x) round(x, digits = 8))) %>% arrange(avg_log2FC)

#DEG.res <- filter(DEG.res, (GL1_2_exp_avg>1.2 | GA1_2_exp_avg>1.2) | (abs(avg_log2FC)>2) & (pct.1>.25 & pct.2>.25))

DEG.res.GSEA.GASR <- DEG.res.GASR$avg_log2FC
names(DEG.res.GSEA.GASR) <- DEG.res.GASR$gene_name
```


```{r, eval=FALSE}
allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1])
```

## GSEA Set 1 {.tabset}

### GA/GL

```{r GA/GL GSEA for Set 1, warning=FALSE, echo=FALSE}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2","Sox4","Klf17","Myc")
set1.GSEA <- invisible(lapply(TF_names, function(target){do.GSEA(targets=targetGenes.set.1[[target]],DEG.res=DEG.res,TF.name=target, comp.title="GA/GL DEG")}))

invisible(sapply(set1.GSEA,function(g){print(g$p1)}))

#sapply(set1.GSEA,function(g){create_dt(g$d1)})

results <- fgsea(pathways = targetGenes.set.1, 
                 stats = DEG.res.GSEA, 
                 minSize = 5,  # Minimum size of a gene set to be considered
                 maxSize = 5000) # Maximum size of a gene set to be considered
results <- results %>% mutate(across(where(is.numeric), \(x) round(x, digits=3)))
create_dt(results)

DEG.res.subset <- lapply(targetGenes.set.1, function(p){filter(DEG.res, gene_name %in% p)})
combined_tibble <- map_dfr(DEG.res.subset, ~ .x, .id = "TF")
create_dt(combined_tibble)
```

### GA/SR

```{r GA/SR GSEA for Set 1, warning=FALSE, echo=FALSE}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2","Sox4","Klf17","Myc")
set1.GSEA <- invisible(lapply(TF_names, function(target){do.GSEA(targets=targetGenes.set.1[[target]],DEG.res=DEG.res.GASR,TF.name=target,comp.title="GA/SR DEG")}))

invisible(sapply(set1.GSEA,function(g){print(g$p1)}))

#sapply(set1.GSEA,function(g){create_dt(g$d1)})

results <- fgsea(pathways = targetGenes.set.1, 
                 stats = DEG.res.GSEA.GASR, 
                 minSize = 5,  # Minimum size of a gene set to be considered
                 maxSize = 5000) # Maximum size of a gene set to be considered
results <- results %>% mutate(across(where(is.numeric), \(x) round(x, digits=3)))
create_dt(results)

DEG.res.subset <- lapply(targetGenes.set.1, function(p){filter(DEG.res.GASR, gene_name %in% p)})
combined_tibble <- map_dfr(DEG.res.subset, ~ .x, .id = "TF")
create_dt(combined_tibble)
```

## GSEA Set 2 {.tabset}

### GA/GL

```{r GA/GL GSEA for Set 2, warning=FALSE}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2")
set2.GSEA <- lapply(TF_names, function(target){do.GSEA(targets=targetGenes.set.2[[target]],DEG.res=DEG.res,TF.name=target, comp.title="GA/GL DEG")})

invisible(sapply(set2.GSEA,function(g){print(g$p1)}))

#sapply(set1.GSEA,function(g){create_dt(g$d1)})

results <- fgsea(pathways = targetGenes.set.2, 
                 stats = DEG.res.GSEA, 
                 minSize = 5,  # Minimum size of a gene set to be considered
                 maxSize = 5000) # Maximum size of a gene set to be considered
results <- results %>% mutate(across(where(is.numeric), \(x) round(x, digits=3)))
create_dt(results)

DEG.res.subset <- lapply(targetGenes.set.2, function(p){filter(DEG.res, gene_name %in% p)})
combined_tibble <- map_dfr(DEG.res.subset, ~ .x, .id = "TF")
create_dt(combined_tibble)
```

### GA/SR

```{r GA/SR GSEA for Set 2, warning=FALSE, echo=FALSE}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2","Sox4","Klf17","Myc")
set1.GSEA <- invisible(lapply(TF_names, function(target){do.GSEA(targets=targetGenes.set.2[[target]],DEG.res=DEG.res.GASR,TF.name=target,comp.title="GA/SR DEG")}))

invisible(sapply(set1.GSEA,function(g){print(g$p1)}))

#sapply(set1.GSEA,function(g){create_dt(g$d1)})

results <- fgsea(pathways = targetGenes.set.2, 
                 stats = DEG.res.GSEA.GASR, 
                 minSize = 5,  # Minimum size of a gene set to be considered
                 maxSize = 5000) # Maximum size of a gene set to be considered
results <- results %>% mutate(across(where(is.numeric), \(x) round(x, digits=3)))
create_dt(results)

DEG.res.subset <- lapply(targetGenes.set.2, function(p){filter(DEG.res.GASR, gene_name %in% p)})
combined_tibble <- map_dfr(DEG.res.subset, ~ .x, .id = "TF")
create_dt(combined_tibble)
```

## GSEA Set 3 {.tabset}

### GA/GL

```{r GA/GL GSEA for Set 3, warning=FALSE}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2")
set3.GSEA <- lapply(TF_names, function(target){do.GSEA(targets=targetGenes.set.3[[target]],DEG.res=DEG.res,TF.name=target, comp.title="GA/GL DEG")})

invisible(sapply(set3.GSEA,function(g){print(g$p1)}))

#sapply(set1.GSEA,function(g){create_dt(g$d1)})

results <- fgsea(pathways = targetGenes.set.3, 
                 stats = DEG.res.GSEA, 
                 minSize = 5,  # Minimum size of a gene set to be considered
                 maxSize = 5000) # Maximum size of a gene set to be considered
results <- results %>% mutate(across(where(is.numeric), \(x) round(x, digits=3)))
create_dt(results)

DEG.res.subset <- lapply(targetGenes.set.3, function(p){filter(DEG.res, gene_name %in% p)})
combined_tibble <- map_dfr(DEG.res.subset, ~ .x, .id = "TF")
create_dt(combined_tibble)
```


## GSEA Set 4 

```{r GSEA for Set 4, warning=FALSE}
TF_names <- c("Tal1","Gata2","Gata3","Vsx2")
set4.GSEA <- lapply(TF_names, function(target){do.GSEA(targets=targetGenes.set.4[[target]],DEG.res=DEG.res,TF.name=target)})

invisible(sapply(set4.GSEA,function(g){print(g$p1)}))

results <- fgsea(pathways = targetGenes.set.4, 
                 stats = DEG.res.GSEA, 
                 minSize = 5,  # Minimum size of a gene set to be considered
                 maxSize = 5000) # Maximum size of a gene set to be considered
results <- results %>% mutate(across(where(is.numeric), \(x) round(x, digits=3)))
create_dt(results)

DEG.res.subset <- lapply(targetGenes.set.3, function(p){filter(DEG.res.GASR, gene_name %in% p)})

combined_tibble <- map_dfr(DEG.res.subset, ~ .x, .id = "TF")
create_dt(combined_tibble)
```

<!-- # GO enrichments 25-25-25 among target genes (C&T overlap incl.) {.tabset} -->

<!-- ```{r Connect Ensembl to fetch GO and set thresholds} -->
<!-- # Connect to the Ensembl database -->
<!-- ensembl <- useMart("ENSEMBL_MART_ENSEMBL", dataset = "mmusculus_gene_ensembl", host="https://nov2020.archive.ensembl.org") -->
<!-- gene_names_with_go <- getBM(attributes = c('external_gene_name', 'go_id'), -->
<!--                        filters = 'with_go', # This dplyr::filter is to only fetch genes with GO IDs -->
<!--                        values = TRUE, -->
<!--                        mart = ensembl) -->
<!-- # Split the data.frame into a list where each element is a character vector of GO IDs, -->
<!-- # and the names of the list elements are the Ensembl gene IDs -->
<!-- geneID2GO <- split(gene_names_with_go$go_id, gene_names_with_go$external_gene_name) -->
<!-- GO2geneID <- split(gene_names_with_go$external_gene_name,gene_names_with_go$go_id) -->
<!-- # Optionally, you can remove genes with no GO IDs if any exist -->
<!-- geneID2GO <- geneID2GO[sapply(geneID2GO, length) > 0] -->
<!-- ``` -->

<!-- ## Tal1 targets -->

<!-- ### Up in GA -->

<!-- ```{r} -->
<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Tal1, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->
<!-- ### Neutral -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Tal1, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->

<!-- ### Up in GL -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Tal1, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->

<!-- ## Gata2 targets -->

<!-- ### Up in GA -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata2, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->
<!-- ### Neutral -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata2, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->

<!-- ### Up in GL -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata2, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->


<!-- ## Gata3 targets -->

<!-- ### Up in GA -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata3, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->
<!-- ### Neutral -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata3, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->

<!-- ### Up in GL -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Gata3, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->



<!-- ## Vsx2 targets -->

<!-- ### Up in GA -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Vsx2, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->

<!-- ### Neutral -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Vsx2, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->

<!-- ### Up in GL -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Vsx2, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->


<!-- ## Sox4 targets -->

<!-- ### Up in GA -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Sox4, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC>upper.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->
<!-- ### Neutral -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Sox4, gene_name), DEG.res$gene_name[mid.lower.index:mid.upper.index]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->

<!-- ### Up in GL -->

<!-- ```{r} -->
<!-- allGenes.list <- unique(dbGetQuery(con, 'SELECT DISTINCT gene_name FROM gene_metadata as gm, links as li WHERE li.ensg_id=gm.ensg_id AND li.zscore>2;')[,1]) -->

<!-- geneList.fac <- as.factor(ifelse(allGenes.list %in% intersect(pull(targets.Sox4, gene_name), DEG.res$gene_name[DEG.res$avg_log2FC<lower.limit]), 1,0)) -->
<!-- names(geneList.fac) <- allGenes.list -->

<!-- sampleGOdata <- new("topGOdata", description = "Simple session", ontology = "BP", -->
<!-- allGenes = geneList.fac, -->
<!-- nodeSize = 5, -->
<!-- annot = annFUN.gene2GO, gene2GO = geneID2GO) -->

<!-- resultFisher <- runTest(sampleGOdata, algorithm = "classic", statistic = "fisher") -->
<!-- allRes <- as_tibble(GenTable(sampleGOdata, classicFisher = resultFisher, ranksOf = "classicFisher", topNodes = 25)) -->

<!-- genes.in.classes <- sapply(allRes$GO.ID,function(GO_id){ -->
<!--   tmp.genes <- intersect(genesInTerm(sampleGOdata, GO_id)[[1]], sigGenes(sampleGOdata)) -->
<!--   return(paste(tmp.genes, collapse = ", ")) -->
<!--   }) -->

<!-- allRes$genes.in.classes <- genes.in.classes -->

<!-- create_dt(allRes) -->
<!-- sigGenes(sampleGOdata) -->
<!-- ``` -->

```{r}
sessionInfo()
```

